# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.ibm_authentication_methods_params import IBMAuthenticationMethodsParams
from typing import Set
from typing_extensions import Self

class ArchivalIBMExternalTargetParams(BaseModel):
    """
    Specifies the parameters for archival to IBM Cloud Object Storage(COS) external targets.
    """ # noqa: E501
    authentication_method: IBMAuthenticationMethodsParams = Field(alias="authenticationMethod")
    bucket_name: Optional[StrictStr] = Field(description="Specifies bucket name of the external target.", alias="bucketName")
    endpoint: Optional[StrictStr] = Field(default=None, description="Specifies the complete endpoint to be used by the Cohesity cluster to access the external target. If specified, location and endpointType parameters are ignored. For example, an endpoint would look like s3.direct.us-east.cloud-object-storage.appdomain.cloud (direct endpoint) OR s3.us-east.cloud-object-storage.appdomain.cloud (public endpoint).")
    endpoint_for_connectors: Optional[StrictStr] = Field(default=None, description="Specifies the complete endpoint to be used by the data-source connector(s) to access the external target. If not specified, 'endpoint' parameter is used. If 'endpoint' parameter is also not specified, endpoint constructed by 'location' and 'endpointType' would be used by the data-source connector(s) to access the external target.", alias="endpointForConnectors")
    endpoint_type: Optional[StrictStr] = Field(default=None, description="Specifies the endpoint type to be used to access the external target. The endpoint used by the Cohesity cluster or data-source connectors is constructed using 'endpointType' and 'location' as follows, s3[.endpointType].[location].cloud-object-storage.appdomaincloud. Eg. s3.private.us-east.cloud-object-storage.appdomain.cloud", alias="endpointType")
    location: Optional[StrictStr] = Field(description="Specifies location of the external target. A location can be a geo(Ex. us-geo), region(Ex. us-east) or a datacenter site (Ex. sjc04) and is used to identify the external target endpoint.")
    is_forever_incremental_archival_enabled: Optional[StrictBool] = Field(default=None, description="Specifies if Forever Incremental Archival setting is enabled or not. Check the documentation for details.", alias="isForeverIncrementalArchivalEnabled")
    is_incremental_archival_enabled: Optional[StrictBool] = Field(default=None, description="Specifies if Incremental Archival setting is enabled or not. Check the documentation for details.", alias="isIncrementalArchivalEnabled")
    source_side_deduplication: Optional[StrictBool] = Field(default=None, description="Specifies the Source Side Deduplication setting for the IBM COS external target. If set to true deduplication is done before sending data to the external target.", alias="sourceSideDeduplication")
    storage_class: Optional[StrictStr] = Field(description="Specifies the IBM COS external target storage class.", alias="storageClass")
    __properties: ClassVar[List[str]] = ["authenticationMethod", "bucketName", "endpoint", "endpointForConnectors", "endpointType", "location", "isForeverIncrementalArchivalEnabled", "isIncrementalArchivalEnabled", "sourceSideDeduplication", "storageClass"]

    @field_validator('endpoint_type')
    def endpoint_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Private', 'Public', 'Direct']):
            raise ValueError("must be one of enum values ('Private', 'Public', 'Direct')")
        return value

    @field_validator('storage_class')
    def storage_class_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['IBMCOSStandard', 'IBMCOSSmartTier', 'IBMCOSVault', 'IBMCOSColdVault']):
            raise ValueError("must be one of enum values ('IBMCOSStandard', 'IBMCOSSmartTier', 'IBMCOSVault', 'IBMCOSColdVault')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArchivalIBMExternalTargetParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of authentication_method
        if self.authentication_method:
            _dict['authenticationMethod'] = self.authentication_method.to_dict()
        # set to None if bucket_name (nullable) is None
        # and model_fields_set contains the field
        if self.bucket_name is None and "bucket_name" in self.model_fields_set:
            _dict['bucketName'] = None

        # set to None if endpoint (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint is None and "endpoint" in self.model_fields_set:
            _dict['endpoint'] = None

        # set to None if endpoint_for_connectors (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_for_connectors is None and "endpoint_for_connectors" in self.model_fields_set:
            _dict['endpointForConnectors'] = None

        # set to None if endpoint_type (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint_type is None and "endpoint_type" in self.model_fields_set:
            _dict['endpointType'] = None

        # set to None if location (nullable) is None
        # and model_fields_set contains the field
        if self.location is None and "location" in self.model_fields_set:
            _dict['location'] = None

        # set to None if is_forever_incremental_archival_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.is_forever_incremental_archival_enabled is None and "is_forever_incremental_archival_enabled" in self.model_fields_set:
            _dict['isForeverIncrementalArchivalEnabled'] = None

        # set to None if is_incremental_archival_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.is_incremental_archival_enabled is None and "is_incremental_archival_enabled" in self.model_fields_set:
            _dict['isIncrementalArchivalEnabled'] = None

        # set to None if source_side_deduplication (nullable) is None
        # and model_fields_set contains the field
        if self.source_side_deduplication is None and "source_side_deduplication" in self.model_fields_set:
            _dict['sourceSideDeduplication'] = None

        # set to None if storage_class (nullable) is None
        # and model_fields_set contains the field
        if self.storage_class is None and "storage_class" in self.model_fields_set:
            _dict['storageClass'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArchivalIBMExternalTargetParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authenticationMethod": IBMAuthenticationMethodsParams.from_dict(obj["authenticationMethod"]) if obj.get("authenticationMethod") is not None else None,
            "bucketName": obj.get("bucketName"),
            "endpoint": obj.get("endpoint"),
            "endpointForConnectors": obj.get("endpointForConnectors"),
            "endpointType": obj.get("endpointType"),
            "location": obj.get("location"),
            "isForeverIncrementalArchivalEnabled": obj.get("isForeverIncrementalArchivalEnabled"),
            "isIncrementalArchivalEnabled": obj.get("isIncrementalArchivalEnabled"),
            "sourceSideDeduplication": obj.get("sourceSideDeduplication"),
            "storageClass": obj.get("storageClass")
        })
        return _obj


