# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class AwsIAmRolesAnywhereParams(BaseModel):
    """
    Specifies the parameters which are specific to IAmRolesAnywhere Authentication Method for AWS External Target.
    """ # noqa: E501
    certificate: Optional[StrictStr] = Field(description="The certificate the customer obtains from the CA.")
    private_key: Optional[StrictStr] = Field(description="The encrypted private key generated by the CA. Using the CA private key, we can sign client certificates on customers behalf and use them to gain access to customer's AWS account.", alias="privateKey")
    profile: Optional[StrictStr] = Field(description="A profile defined with IAM policies, to specify what operations are allowed with the temporary credentials.")
    role: Optional[StrictStr] = Field(description="IAM role which trusts the IAM Roles Anywhere service principal.")
    trust_anchor: Optional[StrictStr] = Field(description="Trust anchor to use for authentication. A trust anchor is a reference to either AWS Private CA or an external CA.", alias="trustAnchor")
    __properties: ClassVar[List[str]] = ["certificate", "privateKey", "profile", "role", "trustAnchor"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AwsIAmRolesAnywhereParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if certificate (nullable) is None
        # and model_fields_set contains the field
        if self.certificate is None and "certificate" in self.model_fields_set:
            _dict['certificate'] = None

        # set to None if private_key (nullable) is None
        # and model_fields_set contains the field
        if self.private_key is None and "private_key" in self.model_fields_set:
            _dict['privateKey'] = None

        # set to None if profile (nullable) is None
        # and model_fields_set contains the field
        if self.profile is None and "profile" in self.model_fields_set:
            _dict['profile'] = None

        # set to None if role (nullable) is None
        # and model_fields_set contains the field
        if self.role is None and "role" in self.model_fields_set:
            _dict['role'] = None

        # set to None if trust_anchor (nullable) is None
        # and model_fields_set contains the field
        if self.trust_anchor is None and "trust_anchor" in self.model_fields_set:
            _dict['trustAnchor'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AwsIAmRolesAnywhereParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "certificate": obj.get("certificate"),
            "privateKey": obj.get("privateKey"),
            "profile": obj.get("profile"),
            "role": obj.get("role"),
            "trustAnchor": obj.get("trustAnchor")
        })
        return _obj


