# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class AwsCredentials(BaseModel):
    """
    Specifies the object to Aws related credentials.
    """ # noqa: E501
    auth_type: Optional[StrictStr] = Field(default=None, description="Specifies the type of authentication being used in the request.", alias="authType")
    directory_dns_address: Optional[StrictStr] = Field(default=None, description="Specifies the DNS address of the AWS managed active directory in which. Currently is set only for kerberos authentication.", alias="directoryDNSAddress")
    password: Optional[StrictStr] = Field(default=None, description="Specifies the password to access target entity.")
    realm_name: Optional[StrictStr] = Field(default=None, description="Specifies the Kerberos realm name for a Kerberos-secured target.", alias="realmName")
    username: Optional[StrictStr] = Field(default=None, description="Specifies the username to access target entity.")
    __properties: ClassVar[List[str]] = ["authType", "directoryDNSAddress", "password", "realmName", "username"]

    @field_validator('auth_type')
    def auth_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kUseIAMUser', 'kUseIAMRole', 'kUseInstanceProfile', 'kStandardCredentials', 'kKerberos']):
            raise ValueError("must be one of enum values ('kUseIAMUser', 'kUseIAMRole', 'kUseInstanceProfile', 'kStandardCredentials', 'kKerberos')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AwsCredentials from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if auth_type (nullable) is None
        # and model_fields_set contains the field
        if self.auth_type is None and "auth_type" in self.model_fields_set:
            _dict['authType'] = None

        # set to None if directory_dns_address (nullable) is None
        # and model_fields_set contains the field
        if self.directory_dns_address is None and "directory_dns_address" in self.model_fields_set:
            _dict['directoryDNSAddress'] = None

        # set to None if password (nullable) is None
        # and model_fields_set contains the field
        if self.password is None and "password" in self.model_fields_set:
            _dict['password'] = None

        # set to None if realm_name (nullable) is None
        # and model_fields_set contains the field
        if self.realm_name is None and "realm_name" in self.model_fields_set:
            _dict['realmName'] = None

        # set to None if username (nullable) is None
        # and model_fields_set contains the field
        if self.username is None and "username" in self.model_fields_set:
            _dict['username'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AwsCredentials from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authType": obj.get("authType"),
            "directoryDNSAddress": obj.get("directoryDNSAddress"),
            "password": obj.get("password"),
            "realmName": obj.get("realmName"),
            "username": obj.get("username")
        })
        return _obj


