# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.assess_software_update_params import AssessSoftwareUpdateParams
from cohesity_sdk.helios.models.patch_params import PatchParams
from cohesity_sdk.helios.models.upgrade_params import UpgradeParams
from typing import Set
from typing_extensions import Self

class ClusterSWUpdateParams(BaseModel):
    """
    Specifies the parameters to update the software on the cluster.
    """ # noqa: E501
    assess_software_update_params: Optional[AssessSoftwareUpdateParams] = Field(default=None, alias="assessSoftwareUpdateParams")
    node_type: Optional[StrictStr] = Field(default=None, description="Type of node where upgrade has to be performed using the provided package. * `ClusterNode` * `ConnectorNode` nodeType is only applicable for following operation types. * `DownloadUpgradePackage` * `DownloadPatchPackage` * `DownloadUpgradeAndPatchPackages` ", alias="nodeType")
    operation_type: StrictStr = Field(description="The operation type. * `DownloadUpgradePackage` - Operation to download upgrade package. * `DownloadPatchPackage` - Operation to download patch package. * `DownloadUpgradeAndPatchPackages` - Operation to download upgrade    and patch packages. * `DownloadAndUpgrade` - Operation to download package and    and then upgrade the cluster. * `DownloadAndApplyPatch` - Operation to download package and    and then apply the patch. * `DownloadAndUpgradeWithPatch` - Operation to download upgrade   and patch packages, and then, upgrade the cluster and immediately   patch it * `Upgrade` - Operation to upgrade the software on the cluster. * `ApplyPatch` - Operation to apply the patch. * `RevertPatch` - Operation to revert the patch. * `UpgradeAndPatch` - Operation to upgrade the software on the   cluster and apply a patch. * `AssessSoftwareUpdate` - Operation to perform checks to assess   the state of cluster pre/post software update (upgrade/patch). * `AbortApplyPatch` - Operation to abort the patch. * `AbortUpgrade` - Operation to abort the upgrade. ", alias="operationType")
    patch_params: Optional[PatchParams] = Field(default=None, alias="patchParams")
    upgrade_params: Optional[UpgradeParams] = Field(default=None, alias="upgradeParams")
    __properties: ClassVar[List[str]] = ["assessSoftwareUpdateParams", "nodeType", "operationType", "patchParams", "upgradeParams"]

    @field_validator('node_type')
    def node_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ClusterNode', 'FreeNode', 'ConnectorNode']):
            raise ValueError("must be one of enum values ('ClusterNode', 'FreeNode', 'ConnectorNode')")
        return value

    @field_validator('operation_type')
    def operation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['DownloadUpgradePackage', 'DownloadPatchPackage', 'DownloadUpgradeAndPatchPackages', 'DownloadAndUpgrade', 'DownloadAndApplyPatch', 'DownloadAndUpgradeWithPatch', 'Upgrade', 'ApplyPatch', 'RevertPatch', 'UpgradeAndPatch', 'AssessSoftwareUpdate', 'AbortApplyPatch', 'AbortUpgrade']):
            raise ValueError("must be one of enum values ('DownloadUpgradePackage', 'DownloadPatchPackage', 'DownloadUpgradeAndPatchPackages', 'DownloadAndUpgrade', 'DownloadAndApplyPatch', 'DownloadAndUpgradeWithPatch', 'Upgrade', 'ApplyPatch', 'RevertPatch', 'UpgradeAndPatch', 'AssessSoftwareUpdate', 'AbortApplyPatch', 'AbortUpgrade')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterSWUpdateParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of assess_software_update_params
        if self.assess_software_update_params:
            _dict['assessSoftwareUpdateParams'] = self.assess_software_update_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of patch_params
        if self.patch_params:
            _dict['patchParams'] = self.patch_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of upgrade_params
        if self.upgrade_params:
            _dict['upgradeParams'] = self.upgrade_params.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterSWUpdateParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "assessSoftwareUpdateParams": AssessSoftwareUpdateParams.from_dict(obj["assessSoftwareUpdateParams"]) if obj.get("assessSoftwareUpdateParams") is not None else None,
            "nodeType": obj.get("nodeType"),
            "operationType": obj.get("operationType"),
            "patchParams": PatchParams.from_dict(obj["patchParams"]) if obj.get("patchParams") is not None else None,
            "upgradeParams": UpgradeParams.from_dict(obj["upgradeParams"]) if obj.get("upgradeParams") is not None else None
        })
        return _obj


