# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.worker_endpoint import WorkerEndpoint
from typing import Set
from typing_extensions import Self

class CommonDataAccessSessionInformation(BaseModel):
    """
    Common Data Access Session Information.
    """ # noqa: E501
    creation_time_usecs: Optional[StrictInt] = Field(default=None, description="Specifies the time at which the session was created.", alias="creationTimeUsecs")
    last_modification_time_usecs: Optional[StrictInt] = Field(default=None, description="Specifies the time at which the session was last modified.", alias="lastModificationTimeUsecs")
    name: Optional[StrictStr] = Field(default=None, description="The name of the data access session.")
    session_id: Optional[StrictStr] = Field(default=None, description="Specifies the id of the data access session.", alias="sessionId")
    status: Optional[StrictStr] = Field(default=None, description="Specifies the status of the Data Access Session. Machine status such as Admitted/WaitingForArchiveDownload/ WaitingForResource/SetupInProgress/Ready/Finished")
    worker_endpoints: Optional[List[WorkerEndpoint]] = Field(default=None, description="Specifies the list of metadata worker endpoints. In case of more than one metadata point client can contact any metadata worker.", alias="workerEndpoints")
    __properties: ClassVar[List[str]] = ["creationTimeUsecs", "lastModificationTimeUsecs", "name", "sessionId", "status", "workerEndpoints"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Pending', 'Established', 'RefreshInitiated', 'Terminated']):
            raise ValueError("must be one of enum values ('Pending', 'Established', 'RefreshInitiated', 'Terminated')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommonDataAccessSessionInformation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "creation_time_usecs",
            "last_modification_time_usecs",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in worker_endpoints (list)
        _items = []
        if self.worker_endpoints:
            for _item_worker_endpoints in self.worker_endpoints:
                if _item_worker_endpoints:
                    _items.append(_item_worker_endpoints.to_dict())
            _dict['workerEndpoints'] = _items
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['sessionId'] = None

        # set to None if worker_endpoints (nullable) is None
        # and model_fields_set contains the field
        if self.worker_endpoints is None and "worker_endpoints" in self.model_fields_set:
            _dict['workerEndpoints'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommonDataAccessSessionInformation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creationTimeUsecs": obj.get("creationTimeUsecs"),
            "lastModificationTimeUsecs": obj.get("lastModificationTimeUsecs"),
            "name": obj.get("name"),
            "sessionId": obj.get("sessionId"),
            "status": obj.get("status"),
            "workerEndpoints": [WorkerEndpoint.from_dict(_item) for _item in obj["workerEndpoints"]] if obj.get("workerEndpoints") is not None else None
        })
        return _obj


