# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.connection_connectivity_status import ConnectionConnectivityStatus
from typing import Set
from typing_extensions import Self

class DataSourceConnection(BaseModel):
    """
    Specifies all the properties of the data-source connection. A connection is specified by an ID that's guaranteed to be unique. A connection is associated with exactly one tenant. A connection can be thought of as a subset of its tenant's connectors and can contain 0 or more connectors within it. A connector can only be associated with one connection at max at a given time.
    """ # noqa: E501
    cluster_vips: Optional[List[StrictStr]] = Field(default=None, description="Specifies the list of cluster virtual IPs associated with the connection.", alias="clusterVips")
    connection_id: StrictStr = Field(description="Specifies the unique ID of the connection.", alias="connectionId")
    connection_name: StrictStr = Field(description="Specifies the name of the connection. For a given tenant, different connections can't have the same name. However, two (or more) different tenants can each have a connection with the same name.", alias="connectionName")
    connection_type: Optional[StrictStr] = Field(default=None, description="Specifies the type of the connection.", alias="connectionType")
    connectivity_status: Optional[ConnectionConnectivityStatus] = Field(default=None, alias="connectivityStatus")
    connector_ids: Optional[List[StrictStr]] = Field(default=None, description="Specifies the IDs of the connectors in this connection.", alias="connectorIds")
    patching_connector_id: Optional[StrictStr] = Field(default=None, description="Specifies the connector ID that is currently in patch.", alias="patchingConnectorId")
    registration_token: Optional[StrictStr] = Field(default=None, description="Specifies a token that can be used to register a connector against this connection", alias="registrationToken")
    tenant_id: Optional[StrictStr] = Field(default=None, description="Specifies the tenant ID of the connection.", alias="tenantId")
    upgrading_connector_id: Optional[StrictStr] = Field(default=None, description="Specifies the connector ID that is currently in upgrade.", alias="upgradingConnectorId")
    __properties: ClassVar[List[str]] = ["clusterVips", "connectionId", "connectionName", "connectionType", "connectivityStatus", "connectorIds", "patchingConnectorId", "registrationToken", "tenantId", "upgradingConnectorId"]

    @field_validator('connection_type')
    def connection_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kDataSourceConnector', 'kHybridExtender']):
            raise ValueError("must be one of enum values ('kDataSourceConnector', 'kHybridExtender')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataSourceConnection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "connector_ids",
            "patching_connector_id",
            "registration_token",
            "tenant_id",
            "upgrading_connector_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of connectivity_status
        if self.connectivity_status:
            _dict['connectivityStatus'] = self.connectivity_status.to_dict()
        # set to None if cluster_vips (nullable) is None
        # and model_fields_set contains the field
        if self.cluster_vips is None and "cluster_vips" in self.model_fields_set:
            _dict['clusterVips'] = None

        # set to None if connection_type (nullable) is None
        # and model_fields_set contains the field
        if self.connection_type is None and "connection_type" in self.model_fields_set:
            _dict['connectionType'] = None

        # set to None if patching_connector_id (nullable) is None
        # and model_fields_set contains the field
        if self.patching_connector_id is None and "patching_connector_id" in self.model_fields_set:
            _dict['patchingConnectorId'] = None

        # set to None if registration_token (nullable) is None
        # and model_fields_set contains the field
        if self.registration_token is None and "registration_token" in self.model_fields_set:
            _dict['registrationToken'] = None

        # set to None if upgrading_connector_id (nullable) is None
        # and model_fields_set contains the field
        if self.upgrading_connector_id is None and "upgrading_connector_id" in self.model_fields_set:
            _dict['upgradingConnectorId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataSourceConnection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clusterVips": obj.get("clusterVips"),
            "connectionId": obj.get("connectionId"),
            "connectionName": obj.get("connectionName"),
            "connectionType": obj.get("connectionType"),
            "connectivityStatus": ConnectionConnectivityStatus.from_dict(obj["connectivityStatus"]) if obj.get("connectivityStatus") is not None else None,
            "connectorIds": obj.get("connectorIds"),
            "patchingConnectorId": obj.get("patchingConnectorId"),
            "registrationToken": obj.get("registrationToken"),
            "tenantId": obj.get("tenantId"),
            "upgradingConnectorId": obj.get("upgradingConnectorId")
        })
        return _obj


