# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.file_stat_info import FileStatInfo
from typing import Set
from typing_extensions import Self

class Directory(BaseModel):
    """
    Directory is the struct to represent a file or a folder on a VM.
    """ # noqa: E501
    file_stat_info: Optional[FileStatInfo] = Field(default=None, alias="fileStatInfo")
    full_path: Optional[StrictStr] = Field(default=None, description="Path of the file/directory.", alias="fullPath")
    item_id: Optional[StrictStr] = Field(default=None, description="ItemId is the id of the file/directory. Currently only used in case of OneDrive files/directories.", alias="itemId")
    name: Optional[StrictStr] = Field(default=None, description="Name is the name of the file or folder. For /test/file.txt, name will be file.txt.")
    type: Optional[StrictStr] = Field(default=None, description="Specifies the file type.")
    __properties: ClassVar[List[str]] = ["fileStatInfo", "fullPath", "itemId", "name", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['File', 'Directory', 'Symlink']):
            raise ValueError("must be one of enum values ('File', 'Directory', 'Symlink')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Directory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of file_stat_info
        if self.file_stat_info:
            _dict['fileStatInfo'] = self.file_stat_info.to_dict()
        # set to None if full_path (nullable) is None
        # and model_fields_set contains the field
        if self.full_path is None and "full_path" in self.model_fields_set:
            _dict['fullPath'] = None

        # set to None if item_id (nullable) is None
        # and model_fields_set contains the field
        if self.item_id is None and "item_id" in self.model_fields_set:
            _dict['itemId'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Directory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fileStatInfo": FileStatInfo.from_dict(obj["fileStatInfo"]) if obj.get("fileStatInfo") is not None else None,
            "fullPath": obj.get("fullPath"),
            "itemId": obj.get("itemId"),
            "name": obj.get("name"),
            "type": obj.get("type")
        })
        return _obj


