# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.aws_snapshot_manager_params import AwsSnapshotManagerParams
from cohesity_sdk.helios.models.common_mssql_protection_group_params import CommonMSSQLProtectionGroupParams
from cohesity_sdk.helios.models.exchange_env_job_params import ExchangeEnvJobParams
from cohesity_sdk.helios.models.externally_triggered_job_params import ExternallyTriggeredJobParams
from cohesity_sdk.helios.models.hyperv_env_job_params import HypervEnvJobParams
from cohesity_sdk.helios.models.nas_env_job_params import NasEnvJobParams
from cohesity_sdk.helios.models.o365_env_job_params import O365EnvJobParams
from cohesity_sdk.helios.models.oracle_env_job_params import OracleEnvJobParams
from cohesity_sdk.helios.models.physical_env_job_params import PhysicalEnvJobParams
from cohesity_sdk.helios.models.san_env_job_params import SanEnvJobParams
from cohesity_sdk.helios.models.vmware_env_job_params import VmwareEnvJobParams
from typing import Set
from typing_extensions import Self

class EnvironmentTypeJobParams(BaseModel):
    """
    Specifies the policy level additional environment specific backup params. If this is not specified, default actions will be taken, for example for NAS environments, all objects within the source will be backed up.
    """ # noqa: E501
    aws_snapshot_params: Optional[AwsSnapshotManagerParams] = Field(default=None, alias="awsSnapshotParams")
    exchange_params: Optional[ExchangeEnvJobParams] = Field(default=None, alias="exchangeParams")
    externally_triggered_job_params: Optional[ExternallyTriggeredJobParams] = Field(default=None, alias="externallyTriggeredJobParams")
    hyperv_params: Optional[HypervEnvJobParams] = Field(default=None, alias="hypervParams")
    nas_params: Optional[NasEnvJobParams] = Field(default=None, alias="nasParams")
    office365_params: Optional[O365EnvJobParams] = Field(default=None, alias="office365Params")
    oracle_params: Optional[OracleEnvJobParams] = Field(default=None, alias="oracleParams")
    physical_params: Optional[PhysicalEnvJobParams] = Field(default=None, alias="physicalParams")
    pure_params: Optional[SanEnvJobParams] = Field(default=None, alias="pureParams")
    sql_params: Optional[CommonMSSQLProtectionGroupParams] = Field(default=None, alias="sqlParams")
    vmware_params: Optional[VmwareEnvJobParams] = Field(default=None, alias="vmwareParams")
    __properties: ClassVar[List[str]] = ["awsSnapshotParams", "exchangeParams", "externallyTriggeredJobParams", "hypervParams", "nasParams", "office365Params", "oracleParams", "physicalParams", "pureParams", "sqlParams", "vmwareParams"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnvironmentTypeJobParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of aws_snapshot_params
        if self.aws_snapshot_params:
            _dict['awsSnapshotParams'] = self.aws_snapshot_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of exchange_params
        if self.exchange_params:
            _dict['exchangeParams'] = self.exchange_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of externally_triggered_job_params
        if self.externally_triggered_job_params:
            _dict['externallyTriggeredJobParams'] = self.externally_triggered_job_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hyperv_params
        if self.hyperv_params:
            _dict['hypervParams'] = self.hyperv_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nas_params
        if self.nas_params:
            _dict['nasParams'] = self.nas_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of office365_params
        if self.office365_params:
            _dict['office365Params'] = self.office365_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of oracle_params
        if self.oracle_params:
            _dict['oracleParams'] = self.oracle_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of physical_params
        if self.physical_params:
            _dict['physicalParams'] = self.physical_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pure_params
        if self.pure_params:
            _dict['pureParams'] = self.pure_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sql_params
        if self.sql_params:
            _dict['sqlParams'] = self.sql_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of vmware_params
        if self.vmware_params:
            _dict['vmwareParams'] = self.vmware_params.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnvironmentTypeJobParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "awsSnapshotParams": AwsSnapshotManagerParams.from_dict(obj["awsSnapshotParams"]) if obj.get("awsSnapshotParams") is not None else None,
            "exchangeParams": ExchangeEnvJobParams.from_dict(obj["exchangeParams"]) if obj.get("exchangeParams") is not None else None,
            "externallyTriggeredJobParams": ExternallyTriggeredJobParams.from_dict(obj["externallyTriggeredJobParams"]) if obj.get("externallyTriggeredJobParams") is not None else None,
            "hypervParams": HypervEnvJobParams.from_dict(obj["hypervParams"]) if obj.get("hypervParams") is not None else None,
            "nasParams": NasEnvJobParams.from_dict(obj["nasParams"]) if obj.get("nasParams") is not None else None,
            "office365Params": O365EnvJobParams.from_dict(obj["office365Params"]) if obj.get("office365Params") is not None else None,
            "oracleParams": OracleEnvJobParams.from_dict(obj["oracleParams"]) if obj.get("oracleParams") is not None else None,
            "physicalParams": PhysicalEnvJobParams.from_dict(obj["physicalParams"]) if obj.get("physicalParams") is not None else None,
            "pureParams": SanEnvJobParams.from_dict(obj["pureParams"]) if obj.get("pureParams") is not None else None,
            "sqlParams": CommonMSSQLProtectionGroupParams.from_dict(obj["sqlParams"]) if obj.get("sqlParams") is not None else None,
            "vmwareParams": VmwareEnvJobParams.from_dict(obj["vmwareParams"]) if obj.get("vmwareParams") is not None else None
        })
        return _obj


