# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.data_tiering_target import DataTieringTarget
from cohesity_sdk.helios.models.uptiering_file_age_policy import UptieringFileAgePolicy
from typing import Set
from typing_extensions import Self

class FileUptieringParams(BaseModel):
    """
    File Uptiering parameters
    """ # noqa: E501
    include_all_files: Optional[StrictBool] = Field(default=False, description="If set, all files in the view will be uptiered regardless of file_select_policy, num_file_access, hot_file_window, file_size constraints.", alias="includeAllFiles")
    target: Optional[DataTieringTarget] = None
    uptiering_file_age: Optional[UptieringFileAgePolicy] = Field(default=None, alias="uptieringFileAge")
    __properties: ClassVar[List[str]] = ["includeAllFiles", "target", "uptieringFileAge"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileUptieringParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of uptiering_file_age
        if self.uptiering_file_age:
            _dict['uptieringFileAge'] = self.uptiering_file_age.to_dict()
        # set to None if include_all_files (nullable) is None
        # and model_fields_set contains the field
        if self.include_all_files is None and "include_all_files" in self.model_fields_set:
            _dict['includeAllFiles'] = None

        # set to None if target (nullable) is None
        # and model_fields_set contains the field
        if self.target is None and "target" in self.model_fields_set:
            _dict['target'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileUptieringParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "includeAllFiles": obj.get("includeAllFiles") if obj.get("includeAllFiles") is not None else False,
            "target": DataTieringTarget.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "uptieringFileAge": UptieringFileAgePolicy.from_dict(obj["uptieringFileAge"]) if obj.get("uptieringFileAge") is not None else None
        })
        return _obj


