# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class GenerateNewStoreCertificateRequest(BaseModel):
    """
    Specifies the parameters to generate a certificate signed by Cohesity CA and store it in secret store. The certificate generated will have a default validity of 365 days. Please contact Cohesity Support to update this value. The maximum validity of the certificate generated can be 397 days.
    """ # noqa: E501
    display_name: Optional[StrictStr] = Field(default=None, description="Display name of the certificate.", alias="displayName")
    common_name: Optional[StrictStr] = Field(default=None, description="Common Name (CN) of the certificate.", alias="commonName")
    organization: Optional[StrictStr] = Field(default=None, description="Organization (O) name of the certificate.")
    organization_unit: Optional[StrictStr] = Field(default=None, description="Organization unit (OU) of the certificate.", alias="organizationUnit")
    valid_till_usecs: Optional[StrictInt] = Field(default=None, description="The date till which the certificate is valid, expressed as a Unix timestamp epoch in microseconds. The validity period must not exceed the maximum allowed duration of 397 days (configurable). If a value exceeding this duration is provided, the request will be rejected with a validation error. If the field is not provided, a default value will be used instead.", alias="validTillUsecs")
    __properties: ClassVar[List[str]] = ["displayName", "commonName", "organization", "organizationUnit", "validTillUsecs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerateNewStoreCertificateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['displayName'] = None

        # set to None if common_name (nullable) is None
        # and model_fields_set contains the field
        if self.common_name is None and "common_name" in self.model_fields_set:
            _dict['commonName'] = None

        # set to None if organization (nullable) is None
        # and model_fields_set contains the field
        if self.organization is None and "organization" in self.model_fields_set:
            _dict['organization'] = None

        # set to None if organization_unit (nullable) is None
        # and model_fields_set contains the field
        if self.organization_unit is None and "organization_unit" in self.model_fields_set:
            _dict['organizationUnit'] = None

        # set to None if valid_till_usecs (nullable) is None
        # and model_fields_set contains the field
        if self.valid_till_usecs is None and "valid_till_usecs" in self.model_fields_set:
            _dict['validTillUsecs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerateNewStoreCertificateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "displayName": obj.get("displayName"),
            "commonName": obj.get("commonName"),
            "organization": obj.get("organization"),
            "organizationUnit": obj.get("organizationUnit"),
            "validTillUsecs": obj.get("validTillUsecs")
        })
        return _obj


