# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class GmailRestoreLabel(BaseModel):
    """
    Specifies a Gmail label or folder to recover.
    """ # noqa: E501
    item_ids: Optional[List[StrictStr]] = Field(default=None, description="Specifies a list of item ids to recover. This field is applicable only if 'recoverEntireLabel' is false.", alias="itemIds")
    label_id: Optional[StrictInt] = Field(default=None, description="Specifies the unique identifier of the label.", alias="labelId")
    label_name: Optional[StrictStr] = Field(default=None, description="Specifies the name of the label.", alias="labelName")
    recover_entire_label: Optional[StrictBool] = Field(default=None, description="Specifies to recover all emails under this label.", alias="recoverEntireLabel")
    __properties: ClassVar[List[str]] = ["itemIds", "labelId", "labelName", "recoverEntireLabel"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GmailRestoreLabel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if item_ids (nullable) is None
        # and model_fields_set contains the field
        if self.item_ids is None and "item_ids" in self.model_fields_set:
            _dict['itemIds'] = None

        # set to None if label_id (nullable) is None
        # and model_fields_set contains the field
        if self.label_id is None and "label_id" in self.model_fields_set:
            _dict['labelId'] = None

        # set to None if label_name (nullable) is None
        # and model_fields_set contains the field
        if self.label_name is None and "label_name" in self.model_fields_set:
            _dict['labelName'] = None

        # set to None if recover_entire_label (nullable) is None
        # and model_fields_set contains the field
        if self.recover_entire_label is None and "recover_entire_label" in self.model_fields_set:
            _dict['recoverEntireLabel'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GmailRestoreLabel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "itemIds": obj.get("itemIds"),
            "labelId": obj.get("labelId"),
            "labelName": obj.get("labelName"),
            "recoverEntireLabel": obj.get("recoverEntireLabel")
        })
        return _obj


