# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.dspm_params import DspmParams
from cohesity_sdk.helios.models.ti_params import TiParams
from typing import Set
from typing_extensions import Self

class IntegrationParams(BaseModel):
    """
    Details of an integration.
    """ # noqa: E501
    dspm_params: Optional[DspmParams] = Field(default=None, alias="dspmParams")
    integration_type: StrictStr = Field(description="Type of security integration.<br> - 'DSPM': Data Security Posture Management.<br> - 'SIEM': Security Information and Event Management.<br> - 'SOAR': Security Orchestration, Automation, and Response.<br> - 'TI': Threat Intelligence. ", alias="integrationType")
    ti_params: Optional[TiParams] = Field(default=None, alias="tiParams")
    __properties: ClassVar[List[str]] = ["dspmParams", "integrationType", "tiParams"]

    @field_validator('integration_type')
    def integration_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['DSPM', 'SIEM', 'SOAR', 'TI']):
            raise ValueError("must be one of enum values ('DSPM', 'SIEM', 'SOAR', 'TI')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrationParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dspm_params
        if self.dspm_params:
            _dict['dspmParams'] = self.dspm_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ti_params
        if self.ti_params:
            _dict['tiParams'] = self.ti_params.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrationParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dspmParams": DspmParams.from_dict(obj["dspmParams"]) if obj.get("dspmParams") is not None else None,
            "integrationType": obj.get("integrationType"),
            "tiParams": TiParams.from_dict(obj["tiParams"]) if obj.get("tiParams") is not None else None
        })
        return _obj


