# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class IpmiSelNonVerboseEntry(BaseModel):
    """
    Specifies each entry in the sel verbose response.
    """ # noqa: E501
    record_assertion_type: Optional[StrictStr] = Field(default=None, description="Specifies whether the event is asserted or not. This is only returned in case of verbose = false.", alias="recordAssertionType")
    record_date: Optional[StrictStr] = Field(default=None, description="Specifies the date on which the record is added to SEL. This is only returned in case of verbose = false.", alias="recordDate")
    record_description: Optional[StrictStr] = Field(default=None, description="Specifies a short description corresponding to the sensor event for which record is added to SEL.", alias="recordDescription")
    record_event: Optional[StrictStr] = Field(default=None, description="Provides a short description related to sensor action. This is only returned in case of verbose = false.", alias="recordEvent")
    record_id: Optional[StrictStr] = Field(default=None, description="Specifies the ID corresponding to record in SEL(System Event Log) for given node.", alias="recordId")
    record_time: Optional[StrictStr] = Field(default=None, description="Specifies the time at which the record is added to SEL. This is only returned in case of verbose = false.", alias="recordTime")
    __properties: ClassVar[List[str]] = ["recordAssertionType", "recordDate", "recordDescription", "recordEvent", "recordId", "recordTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IpmiSelNonVerboseEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if record_assertion_type (nullable) is None
        # and model_fields_set contains the field
        if self.record_assertion_type is None and "record_assertion_type" in self.model_fields_set:
            _dict['recordAssertionType'] = None

        # set to None if record_date (nullable) is None
        # and model_fields_set contains the field
        if self.record_date is None and "record_date" in self.model_fields_set:
            _dict['recordDate'] = None

        # set to None if record_description (nullable) is None
        # and model_fields_set contains the field
        if self.record_description is None and "record_description" in self.model_fields_set:
            _dict['recordDescription'] = None

        # set to None if record_event (nullable) is None
        # and model_fields_set contains the field
        if self.record_event is None and "record_event" in self.model_fields_set:
            _dict['recordEvent'] = None

        # set to None if record_id (nullable) is None
        # and model_fields_set contains the field
        if self.record_id is None and "record_id" in self.model_fields_set:
            _dict['recordId'] = None

        # set to None if record_time (nullable) is None
        # and model_fields_set contains the field
        if self.record_time is None and "record_time" in self.model_fields_set:
            _dict['recordTime'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IpmiSelNonVerboseEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recordAssertionType": obj.get("recordAssertionType"),
            "recordDate": obj.get("recordDate"),
            "recordDescription": obj.get("recordDescription"),
            "recordEvent": obj.get("recordEvent"),
            "recordId": obj.get("recordId"),
            "recordTime": obj.get("recordTime")
        })
        return _obj


