# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.kubernetes_filter_params import KubernetesFilterParams
from cohesity_sdk.helios.models.kubernetes_namespace_recovery_target_config import KubernetesNamespaceRecoveryTargetConfig
from cohesity_sdk.helios.models.kubernetes_pvc_info import KubernetesPvcInfo
from cohesity_sdk.helios.models.kubernetes_recovery_migration_params import KubernetesRecoveryMigrationParams
from cohesity_sdk.helios.models.kubernetes_recovery_object_params import KubernetesRecoveryObjectParams
from cohesity_sdk.helios.models.kubernetes_storage_class_params import KubernetesStorageClassParams
from cohesity_sdk.helios.models.recover_cluster_scoped_resources_params import RecoverClusterScopedResourcesParams
from cohesity_sdk.helios.models.recover_protection_group_run_params import RecoverProtectionGroupRunParams
from cohesity_sdk.helios.models.recovered_or_cloned_vms_rename_config import RecoveredOrClonedVmsRenameConfig
from typing import Set
from typing_extensions import Self

class KubernetesTargetParamsForRecoverKubernetesNamespace(BaseModel):
    """
    Specifies the parameters for recovering a Kubernetes namespace to a Kubernetes source.
    """ # noqa: E501
    exclude_params: Optional[KubernetesFilterParams] = Field(default=None, alias="excludeParams")
    excluded_pvcs: Optional[List[Optional[KubernetesPvcInfo]]] = Field(default=None, description="Specifies the list of pvc to be excluded from recovery. This will be deprecated in the future. This is overridden by the object level param.", alias="excludedPvcs")
    include_params: Optional[KubernetesFilterParams] = Field(default=None, alias="includeParams")
    objects: Optional[List[KubernetesRecoveryObjectParams]] = Field(default=None, description="Specifies the objects to be recovered.")
    preserve_mac_address: Optional[StrictBool] = Field(default=None, description="Specifies whether to preserve mac address for restored vm. Default is false.", alias="preserveMacAddress")
    recover_cluster_scoped_resources: Optional[RecoverClusterScopedResourcesParams] = Field(default=None, alias="recoverClusterScopedResources")
    recover_protection_group_runs_params: Optional[List[RecoverProtectionGroupRunParams]] = Field(default=None, description="Specifies the Protection Group Runs params to recover. All the VM's that are successfully backed up by specified Runs will be recovered. This can be specified along with individual snapshots of VMs. User has to make sure that specified Object snapshots and Protection Group Runs should not have any intersection. For example, user cannot specify multiple Runs which has same Object or an Object snapshot and a Run which has same Object's snapshot.", alias="recoverProtectionGroupRunsParams")
    recover_pvcs_only: Optional[StrictBool] = Field(default=None, description="Specifies whether to recover PVCs only during recovery. This is overridden with the object level settings and will be deprecated in the future.", alias="recoverPvcsOnly")
    recovery_region_migration_params: Optional[KubernetesRecoveryMigrationParams] = Field(default=None, alias="recoveryRegionMigrationParams")
    recovery_target_config: Optional[KubernetesNamespaceRecoveryTargetConfig] = Field(description="Specifies the recovery target configuration of the Namespace recovery.", alias="recoveryTargetConfig")
    recovery_zone_migration_params: Optional[List[KubernetesRecoveryMigrationParams]] = Field(default=None, description="Specifies rules for performing zone migrations during recovery. Used in case of recovery to new location and the namespace being recovered is in a different zone.", alias="recoveryZoneMigrationParams")
    rename_recovered_namespaces_params: Optional[RecoveredOrClonedVmsRenameConfig] = Field(default=None, description="Specifies params to rename the Namespaces that are recovered. If not specified, the original names of the Namespaces are preserved. If a name collision occurs then the Namespace being recovered will overwrite the Namespace already present on the source.", alias="renameRecoveredNamespacesParams")
    skip_cluster_compatibility_check: Optional[StrictBool] = Field(default=None, description="Specifies whether to skip checking if the target cluster, to restore to, is compatible or not. By default restore allowed to compatible cluster only", alias="skipClusterCompatibilityCheck")
    storage_class: Optional[KubernetesStorageClassParams] = Field(default=None, alias="storageClass")
    __properties: ClassVar[List[str]] = ["excludeParams", "excludedPvcs", "includeParams", "objects", "preserveMacAddress", "recoverClusterScopedResources", "recoverProtectionGroupRunsParams", "recoverPvcsOnly", "recoveryRegionMigrationParams", "recoveryTargetConfig", "recoveryZoneMigrationParams", "renameRecoveredNamespacesParams", "skipClusterCompatibilityCheck", "storageClass"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KubernetesTargetParamsForRecoverKubernetesNamespace from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of exclude_params
        if self.exclude_params:
            _dict['excludeParams'] = self.exclude_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in excluded_pvcs (list)
        _items = []
        if self.excluded_pvcs:
            for _item_excluded_pvcs in self.excluded_pvcs:
                if _item_excluded_pvcs:
                    _items.append(_item_excluded_pvcs.to_dict())
            _dict['excludedPvcs'] = _items
        # override the default output from pydantic by calling `to_dict()` of include_params
        if self.include_params:
            _dict['includeParams'] = self.include_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in objects (list)
        _items = []
        if self.objects:
            for _item_objects in self.objects:
                if _item_objects:
                    _items.append(_item_objects.to_dict())
            _dict['objects'] = _items
        # override the default output from pydantic by calling `to_dict()` of recover_cluster_scoped_resources
        if self.recover_cluster_scoped_resources:
            _dict['recoverClusterScopedResources'] = self.recover_cluster_scoped_resources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recover_protection_group_runs_params (list)
        _items = []
        if self.recover_protection_group_runs_params:
            for _item_recover_protection_group_runs_params in self.recover_protection_group_runs_params:
                if _item_recover_protection_group_runs_params:
                    _items.append(_item_recover_protection_group_runs_params.to_dict())
            _dict['recoverProtectionGroupRunsParams'] = _items
        # override the default output from pydantic by calling `to_dict()` of recovery_region_migration_params
        if self.recovery_region_migration_params:
            _dict['recoveryRegionMigrationParams'] = self.recovery_region_migration_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recovery_target_config
        if self.recovery_target_config:
            _dict['recoveryTargetConfig'] = self.recovery_target_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recovery_zone_migration_params (list)
        _items = []
        if self.recovery_zone_migration_params:
            for _item_recovery_zone_migration_params in self.recovery_zone_migration_params:
                if _item_recovery_zone_migration_params:
                    _items.append(_item_recovery_zone_migration_params.to_dict())
            _dict['recoveryZoneMigrationParams'] = _items
        # override the default output from pydantic by calling `to_dict()` of rename_recovered_namespaces_params
        if self.rename_recovered_namespaces_params:
            _dict['renameRecoveredNamespacesParams'] = self.rename_recovered_namespaces_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of storage_class
        if self.storage_class:
            _dict['storageClass'] = self.storage_class.to_dict()
        # set to None if exclude_params (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_params is None and "exclude_params" in self.model_fields_set:
            _dict['excludeParams'] = None

        # set to None if excluded_pvcs (nullable) is None
        # and model_fields_set contains the field
        if self.excluded_pvcs is None and "excluded_pvcs" in self.model_fields_set:
            _dict['excludedPvcs'] = None

        # set to None if include_params (nullable) is None
        # and model_fields_set contains the field
        if self.include_params is None and "include_params" in self.model_fields_set:
            _dict['includeParams'] = None

        # set to None if objects (nullable) is None
        # and model_fields_set contains the field
        if self.objects is None and "objects" in self.model_fields_set:
            _dict['objects'] = None

        # set to None if preserve_mac_address (nullable) is None
        # and model_fields_set contains the field
        if self.preserve_mac_address is None and "preserve_mac_address" in self.model_fields_set:
            _dict['preserveMacAddress'] = None

        # set to None if recover_protection_group_runs_params (nullable) is None
        # and model_fields_set contains the field
        if self.recover_protection_group_runs_params is None and "recover_protection_group_runs_params" in self.model_fields_set:
            _dict['recoverProtectionGroupRunsParams'] = None

        # set to None if recover_pvcs_only (nullable) is None
        # and model_fields_set contains the field
        if self.recover_pvcs_only is None and "recover_pvcs_only" in self.model_fields_set:
            _dict['recoverPvcsOnly'] = None

        # set to None if recovery_target_config (nullable) is None
        # and model_fields_set contains the field
        if self.recovery_target_config is None and "recovery_target_config" in self.model_fields_set:
            _dict['recoveryTargetConfig'] = None

        # set to None if recovery_zone_migration_params (nullable) is None
        # and model_fields_set contains the field
        if self.recovery_zone_migration_params is None and "recovery_zone_migration_params" in self.model_fields_set:
            _dict['recoveryZoneMigrationParams'] = None

        # set to None if rename_recovered_namespaces_params (nullable) is None
        # and model_fields_set contains the field
        if self.rename_recovered_namespaces_params is None and "rename_recovered_namespaces_params" in self.model_fields_set:
            _dict['renameRecoveredNamespacesParams'] = None

        # set to None if skip_cluster_compatibility_check (nullable) is None
        # and model_fields_set contains the field
        if self.skip_cluster_compatibility_check is None and "skip_cluster_compatibility_check" in self.model_fields_set:
            _dict['skipClusterCompatibilityCheck'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KubernetesTargetParamsForRecoverKubernetesNamespace from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "excludeParams": KubernetesFilterParams.from_dict(obj["excludeParams"]) if obj.get("excludeParams") is not None else None,
            "excludedPvcs": [KubernetesPvcInfo.from_dict(_item) for _item in obj["excludedPvcs"]] if obj.get("excludedPvcs") is not None else None,
            "includeParams": KubernetesFilterParams.from_dict(obj["includeParams"]) if obj.get("includeParams") is not None else None,
            "objects": [KubernetesRecoveryObjectParams.from_dict(_item) for _item in obj["objects"]] if obj.get("objects") is not None else None,
            "preserveMacAddress": obj.get("preserveMacAddress"),
            "recoverClusterScopedResources": RecoverClusterScopedResourcesParams.from_dict(obj["recoverClusterScopedResources"]) if obj.get("recoverClusterScopedResources") is not None else None,
            "recoverProtectionGroupRunsParams": [RecoverProtectionGroupRunParams.from_dict(_item) for _item in obj["recoverProtectionGroupRunsParams"]] if obj.get("recoverProtectionGroupRunsParams") is not None else None,
            "recoverPvcsOnly": obj.get("recoverPvcsOnly"),
            "recoveryRegionMigrationParams": KubernetesRecoveryMigrationParams.from_dict(obj["recoveryRegionMigrationParams"]) if obj.get("recoveryRegionMigrationParams") is not None else None,
            "recoveryTargetConfig": KubernetesNamespaceRecoveryTargetConfig.from_dict(obj["recoveryTargetConfig"]) if obj.get("recoveryTargetConfig") is not None else None,
            "recoveryZoneMigrationParams": [KubernetesRecoveryMigrationParams.from_dict(_item) for _item in obj["recoveryZoneMigrationParams"]] if obj.get("recoveryZoneMigrationParams") is not None else None,
            "renameRecoveredNamespacesParams": RecoveredOrClonedVmsRenameConfig.from_dict(obj["renameRecoveredNamespacesParams"]) if obj.get("renameRecoveredNamespacesParams") is not None else None,
            "skipClusterCompatibilityCheck": obj.get("skipClusterCompatibilityCheck"),
            "storageClass": KubernetesStorageClassParams.from_dict(obj["storageClass"]) if obj.get("storageClass") is not None else None
        })
        return _obj


