# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cohesity_sdk.helios.models.identity_set import IdentitySet
from typing import Set
from typing_extensions import Self

class M365BackupControllerBillingResponseParams(BaseModel):
    """
    Specifies the response parameters for triggering enable MBS service.
    """ # noqa: E501
    grace_period_end_time_secs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The expiration time of the grace period in epoch secs.", alias="gracePeriodEndTimeSecs")
    id: Optional[StrictStr] = Field(default=None, description="Specifies the Service App ID")
    last_modified_by: Optional[IdentitySet] = Field(default=None, alias="lastModifiedBy")
    last_modified_time_secs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Timestamp of the last modification of the entity in epoch secs.", alias="lastModifiedTimeSecs")
    restore_allowed_till_time_secs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The expiration time of the restoration allowed period in epoch secs.", alias="restoreAllowedTillTimeSecs")
    status: Optional[StrictStr] = Field(default=None, description="Specifies the Status of service.")
    __properties: ClassVar[List[str]] = ["gracePeriodEndTimeSecs", "id", "lastModifiedBy", "lastModifiedTimeSecs", "restoreAllowedTillTimeSecs", "status"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Disabled', 'Enabled', 'ProtectionChangeLocked', 'RestoreLocked', 'UnknownFutureValue']):
            raise ValueError("must be one of enum values ('Disabled', 'Enabled', 'ProtectionChangeLocked', 'RestoreLocked', 'UnknownFutureValue')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of M365BackupControllerBillingResponseParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_modified_by
        if self.last_modified_by:
            _dict['lastModifiedBy'] = self.last_modified_by.to_dict()
        # set to None if grace_period_end_time_secs (nullable) is None
        # and model_fields_set contains the field
        if self.grace_period_end_time_secs is None and "grace_period_end_time_secs" in self.model_fields_set:
            _dict['gracePeriodEndTimeSecs'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if last_modified_time_secs (nullable) is None
        # and model_fields_set contains the field
        if self.last_modified_time_secs is None and "last_modified_time_secs" in self.model_fields_set:
            _dict['lastModifiedTimeSecs'] = None

        # set to None if restore_allowed_till_time_secs (nullable) is None
        # and model_fields_set contains the field
        if self.restore_allowed_till_time_secs is None and "restore_allowed_till_time_secs" in self.model_fields_set:
            _dict['restoreAllowedTillTimeSecs'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of M365BackupControllerBillingResponseParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gracePeriodEndTimeSecs": obj.get("gracePeriodEndTimeSecs"),
            "id": obj.get("id"),
            "lastModifiedBy": IdentitySet.from_dict(obj["lastModifiedBy"]) if obj.get("lastModifiedBy") is not None else None,
            "lastModifiedTimeSecs": obj.get("lastModifiedTimeSecs"),
            "restoreAllowedTillTimeSecs": obj.get("restoreAllowedTillTimeSecs"),
            "status": obj.get("status")
        })
        return _obj


