# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.usage_stats_by_feature import UsageStatsByFeature
from cohesity_sdk.helios.models.usage_stats_by_product import UsageStatsByProduct
from typing import Set
from typing_extensions import Self

class McmLicenseUsageStats(BaseModel):
    """
    This will return the response based on the Type query param. if no Type is available then it will return the overall usage. If Type is available in the query param then it will return the onPrem usage for the clusters based on the type.
    """ # noqa: E501
    usage_stats_by_feature: Optional[UsageStatsByFeature] = Field(default=None, alias="usageStatsByFeature")
    usage_stats_by_product: Optional[UsageStatsByProduct] = Field(default=None, alias="usageStatsByProduct")
    __properties: ClassVar[List[str]] = ["usageStatsByFeature", "usageStatsByProduct"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of McmLicenseUsageStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage_stats_by_feature
        if self.usage_stats_by_feature:
            _dict['usageStatsByFeature'] = self.usage_stats_by_feature.to_dict()
        # override the default output from pydantic by calling `to_dict()` of usage_stats_by_product
        if self.usage_stats_by_product:
            _dict['usageStatsByProduct'] = self.usage_stats_by_product.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of McmLicenseUsageStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "usageStatsByFeature": UsageStatsByFeature.from_dict(obj["usageStatsByFeature"]) if obj.get("usageStatsByFeature") is not None else None,
            "usageStatsByProduct": UsageStatsByProduct.from_dict(obj["usageStatsByProduct"]) if obj.get("usageStatsByProduct") is not None else None
        })
        return _obj


