# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.service_state import ServiceState
from typing import Set
from typing_extensions import Self

class NodeServicesStates(BaseModel):
    """
    Lists node services states
    """ # noqa: E501
    message: Optional[StrictStr] = Field(default=None, description="Specifies an optional message describing details of the cluster services states.")
    node_id: Optional[StrictInt] = Field(default=None, description="Specifies the id of the node.", alias="nodeId")
    node_ips: Optional[List[StrictStr]] = Field(default=None, description="If the node is not part of any cluster, it returns list of local IPs; otherwise it returns the local IP that matches the cluster subnet.", alias="nodeIps")
    node_sw_version: Optional[StrictStr] = Field(default=None, description="Node Software Version", alias="nodeSwVersion")
    part_of_cluster: Optional[StrictBool] = Field(default=None, description="Specifies weather node is part of a cluster ", alias="partOfCluster")
    services_state: Optional[List[ServiceState]] = Field(default=None, description="Contains node services states", alias="servicesState")
    __properties: ClassVar[List[str]] = ["message", "nodeId", "nodeIps", "nodeSwVersion", "partOfCluster", "servicesState"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NodeServicesStates from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in services_state (list)
        _items = []
        if self.services_state:
            for _item_services_state in self.services_state:
                if _item_services_state:
                    _items.append(_item_services_state.to_dict())
            _dict['servicesState'] = _items
        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if node_id (nullable) is None
        # and model_fields_set contains the field
        if self.node_id is None and "node_id" in self.model_fields_set:
            _dict['nodeId'] = None

        # set to None if node_ips (nullable) is None
        # and model_fields_set contains the field
        if self.node_ips is None and "node_ips" in self.model_fields_set:
            _dict['nodeIps'] = None

        # set to None if node_sw_version (nullable) is None
        # and model_fields_set contains the field
        if self.node_sw_version is None and "node_sw_version" in self.model_fields_set:
            _dict['nodeSwVersion'] = None

        # set to None if part_of_cluster (nullable) is None
        # and model_fields_set contains the field
        if self.part_of_cluster is None and "part_of_cluster" in self.model_fields_set:
            _dict['partOfCluster'] = None

        # set to None if services_state (nullable) is None
        # and model_fields_set contains the field
        if self.services_state is None and "services_state" in self.model_fields_set:
            _dict['servicesState'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NodeServicesStates from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "nodeId": obj.get("nodeId"),
            "nodeIps": obj.get("nodeIps"),
            "nodeSwVersion": obj.get("nodeSwVersion"),
            "partOfCluster": obj.get("partOfCluster"),
            "servicesState": [ServiceState.from_dict(_item) for _item in obj["servicesState"]] if obj.get("servicesState") is not None else None
        })
        return _obj


