# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.o365_calendar_item_restore_exclusion_policy import O365CalendarItemRestoreExclusionPolicy
from cohesity_sdk.helios.models.o365_contact_item_restore_exclusion_policy import O365ContactItemRestoreExclusionPolicy
from cohesity_sdk.helios.models.o365_mail_item_restore_exclusion_policy import O365MailItemRestoreExclusionPolicy
from cohesity_sdk.helios.models.o365_note_item_restore_exclusion_policy import O365NoteItemRestoreExclusionPolicy
from cohesity_sdk.helios.models.o365_task_item_restore_exclusion_policy import O365TaskItemRestoreExclusionPolicy
from typing import Set
from typing_extensions import Self

class O365RestoreExclusionPolicy(BaseModel):
    """
    Specifies the filter policy to be applied for exclusions in Microsoft 365 restores.
    """ # noqa: E501
    calendar_item_policy: Optional[O365CalendarItemRestoreExclusionPolicy] = Field(default=None, alias="calendarItemPolicy")
    contact_item_policy: Optional[O365ContactItemRestoreExclusionPolicy] = Field(default=None, alias="contactItemPolicy")
    mail_item_policy: Optional[O365MailItemRestoreExclusionPolicy] = Field(default=None, alias="mailItemPolicy")
    note_item_policy: Optional[O365NoteItemRestoreExclusionPolicy] = Field(default=None, alias="noteItemPolicy")
    task_item_policy: Optional[O365TaskItemRestoreExclusionPolicy] = Field(default=None, alias="taskItemPolicy")
    __properties: ClassVar[List[str]] = ["calendarItemPolicy", "contactItemPolicy", "mailItemPolicy", "noteItemPolicy", "taskItemPolicy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of O365RestoreExclusionPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of calendar_item_policy
        if self.calendar_item_policy:
            _dict['calendarItemPolicy'] = self.calendar_item_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contact_item_policy
        if self.contact_item_policy:
            _dict['contactItemPolicy'] = self.contact_item_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of mail_item_policy
        if self.mail_item_policy:
            _dict['mailItemPolicy'] = self.mail_item_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of note_item_policy
        if self.note_item_policy:
            _dict['noteItemPolicy'] = self.note_item_policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of task_item_policy
        if self.task_item_policy:
            _dict['taskItemPolicy'] = self.task_item_policy.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of O365RestoreExclusionPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "calendarItemPolicy": O365CalendarItemRestoreExclusionPolicy.from_dict(obj["calendarItemPolicy"]) if obj.get("calendarItemPolicy") is not None else None,
            "contactItemPolicy": O365ContactItemRestoreExclusionPolicy.from_dict(obj["contactItemPolicy"]) if obj.get("contactItemPolicy") is not None else None,
            "mailItemPolicy": O365MailItemRestoreExclusionPolicy.from_dict(obj["mailItemPolicy"]) if obj.get("mailItemPolicy") is not None else None,
            "noteItemPolicy": O365NoteItemRestoreExclusionPolicy.from_dict(obj["noteItemPolicy"]) if obj.get("noteItemPolicy") is not None else None,
            "taskItemPolicy": O365TaskItemRestoreExclusionPolicy.from_dict(obj["taskItemPolicy"]) if obj.get("taskItemPolicy") is not None else None
        })
        return _obj


