# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.helios.models.gflag import Gflag
from typing import Set
from typing_extensions import Self

class ServiceGflags(BaseModel):
    """
    Specifies the gflags for a service.
    """ # noqa: E501
    gflags: Optional[List[Gflag]] = Field(default=None, description="Specifies a list of gflags for the service.")
    service_name: Optional[StrictStr] = Field(default=None, description="Specifies the service name.", alias="serviceName")
    __properties: ClassVar[List[str]] = ["gflags", "serviceName"]

    @field_validator('service_name')
    def service_name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kInvalidService', 'kApollo', 'kBridge', 'kGenie', 'kGenieGofer', 'kMagneto', 'kIris', 'kIrisProxy', 'kNewScribe', 'kStats', 'kYoda', 'kAlerts', 'kKeychain', 'kLogWatcher', 'kStatsCollector', 'kGandalf', 'kNexus', 'kNexusProxy', 'kStorageProxy', 'kRtClient', 'kVaultProxy', 'kSmbProxy', 'kBridgeProxy', 'kLibrarian', 'kGroot', 'kEagleAgent', 'kAthena', 'kBifrostBroker', 'kAtom', 'kYodaAgent', 'kSmb2Proxy', 'kThrottler', 'kElrond', 'kHeimdall', 'kBifrost', 'kIcebox', 'kNodeExporter', 'kCompass', 'kPatch', 'kEtlServer', 'kUpgrader', 'kOs', 'kPushproxClient', 'kPushClient', 'kAegis', 'kNfsProxy', 'kElixirWorkerservice', 'kArgusApp', 'kMetadataservice', 'kSpireServer', 'kSpireAgent', 'kLicensing', 'kShelteredHarborApp', 'kShelteredHarborUda', 'kCohesityCa', 'kInfraoperator', 'kMarketplaceoperator', 'kCohesion', 'kSpireApp', 'kGaia', 'kStargate', 'kAdaptx', 'kNosql', 'KRolloutFlagEvaluator', 'kNbMediaServer']):
            raise ValueError("must be one of enum values ('kInvalidService', 'kApollo', 'kBridge', 'kGenie', 'kGenieGofer', 'kMagneto', 'kIris', 'kIrisProxy', 'kNewScribe', 'kStats', 'kYoda', 'kAlerts', 'kKeychain', 'kLogWatcher', 'kStatsCollector', 'kGandalf', 'kNexus', 'kNexusProxy', 'kStorageProxy', 'kRtClient', 'kVaultProxy', 'kSmbProxy', 'kBridgeProxy', 'kLibrarian', 'kGroot', 'kEagleAgent', 'kAthena', 'kBifrostBroker', 'kAtom', 'kYodaAgent', 'kSmb2Proxy', 'kThrottler', 'kElrond', 'kHeimdall', 'kBifrost', 'kIcebox', 'kNodeExporter', 'kCompass', 'kPatch', 'kEtlServer', 'kUpgrader', 'kOs', 'kPushproxClient', 'kPushClient', 'kAegis', 'kNfsProxy', 'kElixirWorkerservice', 'kArgusApp', 'kMetadataservice', 'kSpireServer', 'kSpireAgent', 'kLicensing', 'kShelteredHarborApp', 'kShelteredHarborUda', 'kCohesityCa', 'kInfraoperator', 'kMarketplaceoperator', 'kCohesion', 'kSpireApp', 'kGaia', 'kStargate', 'kAdaptx', 'kNosql', 'KRolloutFlagEvaluator', 'kNbMediaServer')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServiceGflags from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in gflags (list)
        _items = []
        if self.gflags:
            for _item_gflags in self.gflags:
                if _item_gflags:
                    _items.append(_item_gflags.to_dict())
            _dict['gflags'] = _items
        # set to None if service_name (nullable) is None
        # and model_fields_set contains the field
        if self.service_name is None and "service_name" in self.model_fields_set:
            _dict['serviceName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServiceGflags from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gflags": [Gflag.from_dict(_item) for _item in obj["gflags"]] if obj.get("gflags") is not None else None,
            "serviceName": obj.get("serviceName")
        })
        return _obj


