# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import date
from cohesity_sdk.helios.models.mcm_license_usage_stats import McmLicenseUsageStats

from cohesity_sdk.helios.api_client import ApiClient, RequestSerialized
from cohesity_sdk.helios.api_response import ApiResponse
from cohesity_sdk.helios.rest import RESTResponseType


class LicenseApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_license_usage_stats(
        self,
        type: Annotated[Optional[StrictStr], Field(description="Return the license usage stats based on Type. if no Type is available then it will return the overall usage. If Type is available in the query param then it will return the onPrem usage for the clusters based on the Type.")] = None,
        products: Annotated[Optional[List[StrictStr]], Field(description="Returns the usage details for the products.")] = None,
        usage_month: Annotated[Optional[List[date]], Field(description="Return license usage based on the month and year. Accepted format is 'YYYY-MM-DD. If not defined then send the usage for last 1 year. license usage will be return for the month and year mentioned in date. day will be ignored for response.")] = None,
        region_id: Annotated[Optional[StrictStr], Field(description="This field uniquely represents a region        and is used for making Helios calls to a specific region.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> McmLicenseUsageStats:
        """Get License Usage Stats

        Get license usage stats for the account.

        :param type: Return the license usage stats based on Type. if no Type is available then it will return the overall usage. If Type is available in the query param then it will return the onPrem usage for the clusters based on the Type.
        :type type: str
        :param products: Returns the usage details for the products.
        :type products: List[str]
        :param usage_month: Return license usage based on the month and year. Accepted format is 'YYYY-MM-DD. If not defined then send the usage for last 1 year. license usage will be return for the month and year mentioned in date. day will be ignored for response.
        :type usage_month: List[date]
        :param region_id: This field uniquely represents a region        and is used for making Helios calls to a specific region.
        :type region_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_license_usage_stats_serialize(
            type=type,
            products=products,
            usage_month=usage_month,
            region_id=region_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "McmLicenseUsageStats",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_license_usage_stats_with_http_info(
        self,
        type: Annotated[Optional[StrictStr], Field(description="Return the license usage stats based on Type. if no Type is available then it will return the overall usage. If Type is available in the query param then it will return the onPrem usage for the clusters based on the Type.")] = None,
        products: Annotated[Optional[List[StrictStr]], Field(description="Returns the usage details for the products.")] = None,
        usage_month: Annotated[Optional[List[date]], Field(description="Return license usage based on the month and year. Accepted format is 'YYYY-MM-DD. If not defined then send the usage for last 1 year. license usage will be return for the month and year mentioned in date. day will be ignored for response.")] = None,
        region_id: Annotated[Optional[StrictStr], Field(description="This field uniquely represents a region        and is used for making Helios calls to a specific region.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[McmLicenseUsageStats]:
        """Get License Usage Stats

        Get license usage stats for the account.

        :param type: Return the license usage stats based on Type. if no Type is available then it will return the overall usage. If Type is available in the query param then it will return the onPrem usage for the clusters based on the Type.
        :type type: str
        :param products: Returns the usage details for the products.
        :type products: List[str]
        :param usage_month: Return license usage based on the month and year. Accepted format is 'YYYY-MM-DD. If not defined then send the usage for last 1 year. license usage will be return for the month and year mentioned in date. day will be ignored for response.
        :type usage_month: List[date]
        :param region_id: This field uniquely represents a region        and is used for making Helios calls to a specific region.
        :type region_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_license_usage_stats_serialize(
            type=type,
            products=products,
            usage_month=usage_month,
            region_id=region_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "McmLicenseUsageStats",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_license_usage_stats_without_preload_content(
        self,
        type: Annotated[Optional[StrictStr], Field(description="Return the license usage stats based on Type. if no Type is available then it will return the overall usage. If Type is available in the query param then it will return the onPrem usage for the clusters based on the Type.")] = None,
        products: Annotated[Optional[List[StrictStr]], Field(description="Returns the usage details for the products.")] = None,
        usage_month: Annotated[Optional[List[date]], Field(description="Return license usage based on the month and year. Accepted format is 'YYYY-MM-DD. If not defined then send the usage for last 1 year. license usage will be return for the month and year mentioned in date. day will be ignored for response.")] = None,
        region_id: Annotated[Optional[StrictStr], Field(description="This field uniquely represents a region        and is used for making Helios calls to a specific region.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get License Usage Stats

        Get license usage stats for the account.

        :param type: Return the license usage stats based on Type. if no Type is available then it will return the overall usage. If Type is available in the query param then it will return the onPrem usage for the clusters based on the Type.
        :type type: str
        :param products: Returns the usage details for the products.
        :type products: List[str]
        :param usage_month: Return license usage based on the month and year. Accepted format is 'YYYY-MM-DD. If not defined then send the usage for last 1 year. license usage will be return for the month and year mentioned in date. day will be ignored for response.
        :type usage_month: List[date]
        :param region_id: This field uniquely represents a region        and is used for making Helios calls to a specific region.
        :type region_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_license_usage_stats_serialize(
            type=type,
            products=products,
            usage_month=usage_month,
            region_id=region_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "McmLicenseUsageStats",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_license_usage_stats_serialize(
        self,
        type,
        products,
        usage_month,
        region_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'products': 'csv',
            'usageMonth': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if type is not None:
            
            _query_params.append(('type', type))
            
        if products is not None:
            
            _query_params.append(('products', products))
            
        if usage_month is not None:
            
            _query_params.append(('usageMonth', usage_month))
            
        # process the header parameters
        if region_id is not None:
            _header_params['regionId'] = region_id
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/mcm/licenses/entitlements/stats',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


