# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictBool
from cohesity_sdk.helios.models.provider_instances_list import ProviderInstancesList

from cohesity_sdk.helios.api_client import ApiClient, RequestSerialized
from cohesity_sdk.helios.api_response import ApiResponse
from cohesity_sdk.helios.rest import RESTResponseType


class ProviderInstancesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_provider_instances(
        self,
        instance_ids: Annotated[Optional[List[StrictStr]], Field(description="List of Provider Instance IDs to filter on")] = None,
        regions: Annotated[Optional[List[StrictStr]], Field(description="List of regions to filter Provider Instances on")] = None,
        include_service_instance_status: Annotated[Optional[StrictBool], Field(description="Bool flag to check whether to include other details like cluster details and software version along with status for the service instances.")] = None,
        region_id: Annotated[Optional[StrictStr], Field(description="This field uniquely represents a region        and is used for making Helios calls to a specific region.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ProviderInstancesList:
        """List Provider Instances

        List all the Provider Instances with details. The API returns the detailed listing of provider instances. The providers are responsible for managing the life cycle of instances and this API only intends to provide metadata information about the instances.

        :param instance_ids: List of Provider Instance IDs to filter on
        :type instance_ids: List[str]
        :param regions: List of regions to filter Provider Instances on
        :type regions: List[str]
        :param include_service_instance_status: Bool flag to check whether to include other details like cluster details and software version along with status for the service instances.
        :type include_service_instance_status: bool
        :param region_id: This field uniquely represents a region        and is used for making Helios calls to a specific region.
        :type region_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_provider_instances_serialize(
            instance_ids=instance_ids,
            regions=regions,
            include_service_instance_status=include_service_instance_status,
            region_id=region_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProviderInstancesList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_provider_instances_with_http_info(
        self,
        instance_ids: Annotated[Optional[List[StrictStr]], Field(description="List of Provider Instance IDs to filter on")] = None,
        regions: Annotated[Optional[List[StrictStr]], Field(description="List of regions to filter Provider Instances on")] = None,
        include_service_instance_status: Annotated[Optional[StrictBool], Field(description="Bool flag to check whether to include other details like cluster details and software version along with status for the service instances.")] = None,
        region_id: Annotated[Optional[StrictStr], Field(description="This field uniquely represents a region        and is used for making Helios calls to a specific region.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ProviderInstancesList]:
        """List Provider Instances

        List all the Provider Instances with details. The API returns the detailed listing of provider instances. The providers are responsible for managing the life cycle of instances and this API only intends to provide metadata information about the instances.

        :param instance_ids: List of Provider Instance IDs to filter on
        :type instance_ids: List[str]
        :param regions: List of regions to filter Provider Instances on
        :type regions: List[str]
        :param include_service_instance_status: Bool flag to check whether to include other details like cluster details and software version along with status for the service instances.
        :type include_service_instance_status: bool
        :param region_id: This field uniquely represents a region        and is used for making Helios calls to a specific region.
        :type region_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_provider_instances_serialize(
            instance_ids=instance_ids,
            regions=regions,
            include_service_instance_status=include_service_instance_status,
            region_id=region_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProviderInstancesList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_provider_instances_without_preload_content(
        self,
        instance_ids: Annotated[Optional[List[StrictStr]], Field(description="List of Provider Instance IDs to filter on")] = None,
        regions: Annotated[Optional[List[StrictStr]], Field(description="List of regions to filter Provider Instances on")] = None,
        include_service_instance_status: Annotated[Optional[StrictBool], Field(description="Bool flag to check whether to include other details like cluster details and software version along with status for the service instances.")] = None,
        region_id: Annotated[Optional[StrictStr], Field(description="This field uniquely represents a region        and is used for making Helios calls to a specific region.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Provider Instances

        List all the Provider Instances with details. The API returns the detailed listing of provider instances. The providers are responsible for managing the life cycle of instances and this API only intends to provide metadata information about the instances.

        :param instance_ids: List of Provider Instance IDs to filter on
        :type instance_ids: List[str]
        :param regions: List of regions to filter Provider Instances on
        :type regions: List[str]
        :param include_service_instance_status: Bool flag to check whether to include other details like cluster details and software version along with status for the service instances.
        :type include_service_instance_status: bool
        :param region_id: This field uniquely represents a region        and is used for making Helios calls to a specific region.
        :type region_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_provider_instances_serialize(
            instance_ids=instance_ids,
            regions=regions,
            include_service_instance_status=include_service_instance_status,
            region_id=region_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ProviderInstancesList",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_provider_instances_serialize(
        self,
        instance_ids,
        regions,
        include_service_instance_status,
        region_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'instanceIds': 'csv',
            'regions': 'csv',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if instance_ids is not None:
            
            _query_params.append(('instanceIds', instance_ids))
            
        if regions is not None:
            
            _query_params.append(('regions', regions))
            
        if include_service_instance_status is not None:
            
            _query_params.append(('includeServiceInstanceStatus', include_service_instance_status))
            
        # process the header parameters
        if region_id is not None:
            _header_params['regionId'] = region_id
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'APIKeyHeader'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/mcm/provider-instances',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


