# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.alert_document import AlertDocument
from typing import Set
from typing_extensions import Self

class AlertType(BaseModel):
    """
    Alert type definition
    """ # noqa: E501
    alert_document_list: Optional[List[AlertDocument]] = Field(default=None, description="List of alert message templates", alias="alertDocumentList")
    alert_type_bucket: Optional[StrictStr] = Field(default=None, description="Bucket/category this alert type belongs to", alias="alertTypeBucket")
    alert_type_id: Optional[StrictInt] = Field(default=None, description="Unique identifier for the alert type", alias="alertTypeId")
    category: Optional[StrictStr] = Field(default=None, description="Alert category")
    dedup_interval_seconds: Optional[StrictInt] = Field(default=None, description="Time in seconds before duplicate alerts are allowed", alias="dedupIntervalSeconds")
    dedup_until_resolved: Optional[StrictBool] = Field(default=None, description="Whether deduplication continues until alert is resolved", alias="dedupUntilResolved")
    primary_key_list: Optional[List[StrictStr]] = Field(default=None, description="Properties used for identifying unique alerts", alias="primaryKeyList")
    property_list: Optional[List[StrictStr]] = Field(default=None, description="List of properties used in alert messages", alias="propertyList")
    snmp_notification: Optional[StrictBool] = Field(default=None, description="Whether SNMP notification is enabled", alias="snmpNotification")
    version: Optional[StrictInt] = Field(default=None, description="Version of the alert type definition")
    __properties: ClassVar[List[str]] = ["alertDocumentList", "alertTypeBucket", "alertTypeId", "category", "dedupIntervalSeconds", "dedupUntilResolved", "primaryKeyList", "propertyList", "snmpNotification", "version"]

    @field_validator('alert_type_bucket')
    def alert_type_bucket_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kHardware', 'kSoftware', 'kDataService', 'kMaintenance']):
            raise ValueError("must be one of enum values ('kHardware', 'kSoftware', 'kDataService', 'kMaintenance')")
        return value

    @field_validator('category')
    def category_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kDisk', 'kNode', 'kCluster', 'kChassis', 'kPowerSupply', 'kCPU', 'kMemory', 'kTemperature', 'kFan', 'kNIC', 'kFirmware', 'kNodeHealth', 'kOperatingSystem', 'kDataPath', 'kDataSourceConnector', 'kMetadata', 'kIndexing', 'kHelios', 'kAppMarketPlace', 'kSystemService', 'kLicense', 'kSecurity', 'kUpgrade', 'kClusterManagement', 'kAuditLog', 'kNetworking', 'kConfiguration', 'kStorageUsage', 'kFaultTolerance', 'kBackupRestore', 'kArchivalRestore', 'kRemoteReplication', 'kQuota', 'kCDP', 'kViewFailover', 'kDisasterRecovery', 'kStorageDevice', 'kStoragePool', 'kGeneralSoftwareFailure', 'kAgent', 'kNetBackup']):
            raise ValueError("must be one of enum values ('kDisk', 'kNode', 'kCluster', 'kChassis', 'kPowerSupply', 'kCPU', 'kMemory', 'kTemperature', 'kFan', 'kNIC', 'kFirmware', 'kNodeHealth', 'kOperatingSystem', 'kDataPath', 'kDataSourceConnector', 'kMetadata', 'kIndexing', 'kHelios', 'kAppMarketPlace', 'kSystemService', 'kLicense', 'kSecurity', 'kUpgrade', 'kClusterManagement', 'kAuditLog', 'kNetworking', 'kConfiguration', 'kStorageUsage', 'kFaultTolerance', 'kBackupRestore', 'kArchivalRestore', 'kRemoteReplication', 'kQuota', 'kCDP', 'kViewFailover', 'kDisasterRecovery', 'kStorageDevice', 'kStoragePool', 'kGeneralSoftwareFailure', 'kAgent', 'kNetBackup')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AlertType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in alert_document_list (list)
        _items = []
        if self.alert_document_list:
            for _item_alert_document_list in self.alert_document_list:
                if _item_alert_document_list:
                    _items.append(_item_alert_document_list.to_dict())
            _dict['alertDocumentList'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AlertType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alertDocumentList": [AlertDocument.from_dict(_item) for _item in obj["alertDocumentList"]] if obj.get("alertDocumentList") is not None else None,
            "alertTypeBucket": obj.get("alertTypeBucket"),
            "alertTypeId": obj.get("alertTypeId"),
            "category": obj.get("category"),
            "dedupIntervalSeconds": obj.get("dedupIntervalSeconds"),
            "dedupUntilResolved": obj.get("dedupUntilResolved"),
            "primaryKeyList": obj.get("primaryKeyList"),
            "propertyList": obj.get("propertyList"),
            "snmpNotification": obj.get("snmpNotification"),
            "version": obj.get("version")
        })
        return _obj


