# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.azure_sqldb_protection_group_object_params import AzureSQLDBProtectionGroupObjectParams
from typing import Set
from typing_extensions import Self

class AzureSQLDBProtectionGroupParams(BaseModel):
    """
    Specifies the parameters which are specific to Azure related Protection Groups for Azure SQL DB workload. Objects must be specified.
    """ # noqa: E501
    cdc_data_processing_location: Optional[StrictStr] = Field(default=None, description="Specifies the location where CDC (Change Data Capture) data processing occurs. Valid values are 'Server' (processing on SQL DB server) or 'Client' (processing on Cohesity cluster).", alias="cdcDataProcessingLocation")
    exclude_object_ids: Optional[List[StrictInt]] = Field(default=None, description="Specifies the objects to be excluded in the Protection Group.", alias="excludeObjectIds")
    exclude_sqldb_tag_ids: Optional[List[List[StrictInt]]] = Field(default=None, description="Array of arrays of SQL DB Tag Ids that specify db instances to Exclude.", alias="excludeSQLDBTagIds")
    objects: Optional[List[AzureSQLDBProtectionGroupObjectParams]] = Field(default=None, description="Specifies the objects to be included in the Protection Group.")
    source_id: Optional[StrictInt] = Field(default=None, description="Specifies the id of the parent of the objects.", alias="sourceId")
    source_name: Optional[StrictStr] = Field(default=None, description="Specifies the name of the parent of the objects.", alias="sourceName")
    sql_db_tag_ids: Optional[List[List[StrictInt]]] = Field(default=None, description="Array of arrays of SQL DB Tag Ids that specify db instances to Protect.", alias="sqlDbTagIds")
    __properties: ClassVar[List[str]] = ["cdcDataProcessingLocation", "excludeObjectIds", "excludeSQLDBTagIds", "objects", "sourceId", "sourceName", "sqlDbTagIds"]

    @field_validator('cdc_data_processing_location')
    def cdc_data_processing_location_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Server', 'Client']):
            raise ValueError("must be one of enum values ('Server', 'Client')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AzureSQLDBProtectionGroupParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "source_id",
            "source_name",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in objects (list)
        _items = []
        if self.objects:
            for _item_objects in self.objects:
                if _item_objects:
                    _items.append(_item_objects.to_dict())
            _dict['objects'] = _items
        # set to None if cdc_data_processing_location (nullable) is None
        # and model_fields_set contains the field
        if self.cdc_data_processing_location is None and "cdc_data_processing_location" in self.model_fields_set:
            _dict['cdcDataProcessingLocation'] = None

        # set to None if exclude_sqldb_tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_sqldb_tag_ids is None and "exclude_sqldb_tag_ids" in self.model_fields_set:
            _dict['excludeSQLDBTagIds'] = None

        # set to None if source_id (nullable) is None
        # and model_fields_set contains the field
        if self.source_id is None and "source_id" in self.model_fields_set:
            _dict['sourceId'] = None

        # set to None if source_name (nullable) is None
        # and model_fields_set contains the field
        if self.source_name is None and "source_name" in self.model_fields_set:
            _dict['sourceName'] = None

        # set to None if sql_db_tag_ids (nullable) is None
        # and model_fields_set contains the field
        if self.sql_db_tag_ids is None and "sql_db_tag_ids" in self.model_fields_set:
            _dict['sqlDbTagIds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AzureSQLDBProtectionGroupParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cdcDataProcessingLocation": obj.get("cdcDataProcessingLocation"),
            "excludeObjectIds": obj.get("excludeObjectIds"),
            "excludeSQLDBTagIds": obj.get("excludeSQLDBTagIds"),
            "objects": [AzureSQLDBProtectionGroupObjectParams.from_dict(_item) for _item in obj["objects"]] if obj.get("objects") is not None else None,
            "sourceId": obj.get("sourceId"),
            "sourceName": obj.get("sourceName"),
            "sqlDbTagIds": obj.get("sqlDbTagIds")
        })
        return _obj


