"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from cohesity_sdk.cluster.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from cohesity_sdk.cluster.models.airgap_config import AirgapConfig
    from cohesity_sdk.cluster.models.node_status_result import NodeStatusResult
    from cohesity_sdk.cluster.models.system_app_status_params import SystemAppStatusParams
    globals()['AirgapConfig'] = AirgapConfig
    globals()['NodeStatusResult'] = NodeStatusResult
    globals()['SystemAppStatusParams'] = SystemAppStatusParams


class ClusterStatus(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.

      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.

    """

    allowed_values = {
        ('current_operation',): {
            'None': None,
            'DESTROY': "Destroy",
            'CREATE': "Create",
            'NODEADDITION': "NodeAddition",
            'NODEREMOVAL': "NodeRemoval",
            'DOWNLOADUPGRADEPACKAGE': "DownloadUpgradePackage",
            'DOWNLOADPATCHPACKAGE': "DownloadPatchPackage",
            'DOWNLOADUPGRADEANDPATCHPACKAGES': "DownloadUpgradeAndPatchPackages",
            'DOWNLOADANDUPGRADE': "DownloadAndUpgrade",
            'DOWNLOADANDAPPLYPATCH': "DownloadAndApplyPatch",
            'DOWNLOADANDUPGRADEWITHPATCH': "DownloadAndUpgradeWithPatch",
            'UPGRADE': "Upgrade",
            'APPLYPATCH': "ApplyPatch",
            'REVERTPATCH': "RevertPatch",
            'UPGRADEANDPATCH': "UpgradeAndPatch",
            'ASSESSSOFTWAREUPDATE': "AssessSoftwareUpdate",
            'ABORTAPPLYPATCH': "AbortApplyPatch",
            'ABORTUPGRADE': "AbortUpgrade",
        },
        ('removal_state',): {
            'None': None,
            'KNODEREMOVAL': "kNodeRemoval",
            'KDISKREMOVAL': "kDiskRemoval",
            'KNOREMOVAL': "kNoRemoval",
            'KNODEANDDISKREMOVAL': "kNodeAndDiskRemoval",
        },
        ('stopped_services',): {
            'None': None,
            'KINVALIDSERVICE': "kInvalidService",
            'KAPOLLO': "kApollo",
            'KBRIDGE': "kBridge",
            'KGENIE': "kGenie",
            'KGENIEGOFER': "kGenieGofer",
            'KMAGNETO': "kMagneto",
            'KIRIS': "kIris",
            'KIRISPROXY': "kIrisProxy",
            'KNEWSCRIBE': "kNewScribe",
            'KSTATS': "kStats",
            'KYODA': "kYoda",
            'KALERTS': "kAlerts",
            'KKEYCHAIN': "kKeychain",
            'KLOGWATCHER': "kLogWatcher",
            'KSTATSCOLLECTOR': "kStatsCollector",
            'KGANDALF': "kGandalf",
            'KNEXUS': "kNexus",
            'KNEXUSPROXY': "kNexusProxy",
            'KSTORAGEPROXY': "kStorageProxy",
            'KRTCLIENT': "kRtClient",
            'KVAULTPROXY': "kVaultProxy",
            'KSMBPROXY': "kSmbProxy",
            'KBRIDGEPROXY': "kBridgeProxy",
            'KLIBRARIAN': "kLibrarian",
            'KGROOT': "kGroot",
            'KEAGLEAGENT': "kEagleAgent",
            'KATHENA': "kAthena",
            'KBIFROSTBROKER': "kBifrostBroker",
            'KATOM': "kAtom",
            'KYODAAGENT': "kYodaAgent",
            'KSMB2PROXY': "kSmb2Proxy",
            'KTHROTTLER': "kThrottler",
            'KELROND': "kElrond",
            'KHEIMDALL': "kHeimdall",
            'KBIFROST': "kBifrost",
            'KICEBOX': "kIcebox",
            'KNODEEXPORTER': "kNodeExporter",
            'KCOMPASS': "kCompass",
            'KPATCH': "kPatch",
            'KETLSERVER': "kEtlServer",
            'KUPGRADER': "kUpgrader",
            'KOS': "kOs",
            'KPUSHPROXCLIENT': "kPushproxClient",
            'KPUSHCLIENT': "kPushClient",
            'KAEGIS': "kAegis",
            'KNFSPROXY': "kNfsProxy",
            'KELIXIRWORKERSERVICE': "kElixirWorkerservice",
            'KARGUSAPP': "kArgusApp",
            'KMETADATASERVICE': "kMetadataservice",
            'KSPIRESERVER': "kSpireServer",
            'KSPIREAGENT': "kSpireAgent",
            'KLICENSING': "kLicensing",
            'KSHELTEREDHARBORAPP': "kShelteredHarborApp",
            'KSHELTEREDHARBORUDA': "kShelteredHarborUda",
            'KCOHESITYCA': "kCohesityCa",
            'KINFRAOPERATOR': "kInfraoperator",
            'KMARKETPLACEOPERATOR': "kMarketplaceoperator",
            'KCOHESION': "kCohesion",
            'KSPIREAPP': "kSpireApp",
            'KGAIA': "kGaia",
            'KSTARGATE': "kStargate",
            'KADAPTX': "kAdaptx",
            'KNOSQL': "kNosql",
            'KROLLOUTFLAGEVALUATOR': "KRolloutFlagEvaluator",
        },
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'airgap_config_stats': (AirgapConfig,),  # noqa: E501
            'cluster_id': (int, none_type,),  # noqa: E501
            'cluster_incarnation_id': (int, none_type,),  # noqa: E501
            'current_operation': (str, none_type,),  # noqa: E501
            'message': (str, none_type,),  # noqa: E501
            'name': (str, none_type,),  # noqa: E501
            'node_statuses': ([NodeStatusResult], none_type,),  # noqa: E501
            'removal_state': (str, none_type,),  # noqa: E501
            'services_synced': (bool, none_type,),  # noqa: E501
            'software_version': (str, none_type,),  # noqa: E501
            'stopped_services': ([str], none_type,),  # noqa: E501
            'system_app_status': ([SystemAppStatusParams], none_type,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None



    attribute_map = {
        'airgap_config_stats': 'airgapConfigStats',  # noqa: E501
        'cluster_id': 'clusterId',  # noqa: E501
        'cluster_incarnation_id': 'clusterIncarnationId',  # noqa: E501
        'current_operation': 'currentOperation',  # noqa: E501
        'message': 'message',  # noqa: E501
        'name': 'name',  # noqa: E501
        'node_statuses': 'nodeStatuses',  # noqa: E501
        'removal_state': 'removalState',  # noqa: E501
        'services_synced': 'servicesSynced',  # noqa: E501
        'software_version': 'softwareVersion',  # noqa: E501
        'stopped_services': 'stoppedServices',  # noqa: E501
        'system_app_status': 'systemAppStatus',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ClusterStatus - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)

            airgap_config_stats (AirgapConfig): [optional]  # noqa: E501
            cluster_id (int, none_type): Specifies the id of the cluster.. [optional]  # noqa: E501
            cluster_incarnation_id (int, none_type): Specifies the cluster incarnation id.. [optional]  # noqa: E501
            current_operation (str, none_type): Specifies the current operation of the cluster.. [optional]  # noqa: E501
            message (str, none_type): Specifies an optional message describing details of the cluster status.. [optional]  # noqa: E501
            name (str, none_type): Specifies the name of the cluster.. [optional]  # noqa: E501
            node_statuses ([NodeStatusResult], none_type): Specifies the status of each node on the cluster.. [optional]  # noqa: E501
            removal_state (str, none_type): RemovalState specifies the possible states for removal operations happening on the cluster.. [optional]  # noqa: E501
            services_synced (bool, none_type): Specifies whether or not the services are synced with the list of stopped services.. [optional]  # noqa: E501
            software_version (str, none_type): Specifies the software version of the cluster.. [optional]  # noqa: E501
            stopped_services ([str], none_type): Specifies the service name.. [optional]  # noqa: E501
            system_app_status ([SystemAppStatusParams], none_type): Specifies the status of each system app on the cluster.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)


        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)


