# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.cluster_roles_auth_metadata import ClusterRolesAuthMetadata
from cohesity_sdk.cluster.models.external_target_auth_metadata import ExternalTargetAuthMetadata
from cohesity_sdk.cluster.models.kms_auth_metadata import KmsAuthMetadata
from typing import Set
from typing_extensions import Self

class ClusterAuthMethodsMetadata(BaseModel):
    """
    Specifies the metadata for various authentication methods that can be used to validate the cluster access.
    """ # noqa: E501
    external_target_authentication: Optional[ExternalTargetAuthMetadata] = Field(default=None, alias="externalTargetAuthentication")
    fetch_roles_authentication: ClusterRolesAuthMetadata = Field(alias="fetchRolesAuthentication")
    kms_authentication: Optional[KmsAuthMetadata] = Field(default=None, alias="kmsAuthentication")
    __properties: ClassVar[List[str]] = ["externalTargetAuthentication", "fetchRolesAuthentication", "kmsAuthentication"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterAuthMethodsMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of external_target_authentication
        if self.external_target_authentication:
            _dict['externalTargetAuthentication'] = self.external_target_authentication.to_dict()
        # override the default output from pydantic by calling `to_dict()` of fetch_roles_authentication
        if self.fetch_roles_authentication:
            _dict['fetchRolesAuthentication'] = self.fetch_roles_authentication.to_dict()
        # override the default output from pydantic by calling `to_dict()` of kms_authentication
        if self.kms_authentication:
            _dict['kmsAuthentication'] = self.kms_authentication.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterAuthMethodsMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "externalTargetAuthentication": ExternalTargetAuthMetadata.from_dict(obj["externalTargetAuthentication"]) if obj.get("externalTargetAuthentication") is not None else None,
            "fetchRolesAuthentication": ClusterRolesAuthMetadata.from_dict(obj["fetchRolesAuthentication"]) if obj.get("fetchRolesAuthentication") is not None else None,
            "kmsAuthentication": KmsAuthMetadata.from_dict(obj["kmsAuthentication"]) if obj.get("kmsAuthentication") is not None else None
        })
        return _obj


