# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class CommonRecoveryOptions(BaseModel):
    """
    Configuration options for recovery and conflict resolutions for ServiceNow tables and records.
    """ # noqa: E501
    alternate_column_map: Optional[Dict[str, StrictStr]] = Field(default=None, description="Mapping of alternate columns to be used when the target table lacks the required columns.", alias="alternateColumnMap")
    default_values_for_extra_columns: Optional[StrictStr] = Field(default=None, description="Default values of extra columns", alias="defaultValuesForExtraColumns")
    extra_target_column_action: Optional[StrictStr] = Field(default=None, description="Action when there is a extra column in target table. Default value is skip.", alias="extraTargetColumnAction")
    include_deleted_objects: Optional[StrictBool] = Field(default=None, description="Specifies whether to include deleted Objects in the recovery.", alias="includeDeletedObjects")
    missing_target_column_action: Optional[StrictStr] = Field(default=None, description="Action when column is missing from target table. Default value is create.", alias="missingTargetColumnAction")
    override_row_data: Optional[StrictBool] = Field(default=None, description="Specifies whether to override row data. Default value is true.", alias="overrideRowData")
    preserve_sys_id: Optional[StrictBool] = Field(default=None, description="Specifies whether to preseve sys_id of the restored records", alias="preserveSysId")
    table_not_found_action: Optional[StrictStr] = Field(default=None, description="Action when target table is not found. Default value is error.", alias="tableNotFoundAction")
    __properties: ClassVar[List[str]] = ["alternateColumnMap", "defaultValuesForExtraColumns", "extraTargetColumnAction", "includeDeletedObjects", "missingTargetColumnAction", "overrideRowData", "preserveSysId", "tableNotFoundAction"]

    @field_validator('extra_target_column_action')
    def extra_target_column_action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kError', 'kSkip', 'kCreate', 'kAlternateColumn', 'kSkipColumn', 'kSkipRow', 'kAssignDefault']):
            raise ValueError("must be one of enum values ('kError', 'kSkip', 'kCreate', 'kAlternateColumn', 'kSkipColumn', 'kSkipRow', 'kAssignDefault')")
        return value

    @field_validator('missing_target_column_action')
    def missing_target_column_action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kError', 'kSkip', 'kCreate', 'kAlternateColumn', 'kSkipColumn', 'kSkipRow', 'kAssignDefault']):
            raise ValueError("must be one of enum values ('kError', 'kSkip', 'kCreate', 'kAlternateColumn', 'kSkipColumn', 'kSkipRow', 'kAssignDefault')")
        return value

    @field_validator('table_not_found_action')
    def table_not_found_action_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kError', 'kSkip', 'kCreate', 'kAlternateColumn', 'kSkipColumn', 'kSkipRow', 'kAssignDefault']):
            raise ValueError("must be one of enum values ('kError', 'kSkip', 'kCreate', 'kAlternateColumn', 'kSkipColumn', 'kSkipRow', 'kAssignDefault')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommonRecoveryOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if alternate_column_map (nullable) is None
        # and model_fields_set contains the field
        if self.alternate_column_map is None and "alternate_column_map" in self.model_fields_set:
            _dict['alternateColumnMap'] = None

        # set to None if default_values_for_extra_columns (nullable) is None
        # and model_fields_set contains the field
        if self.default_values_for_extra_columns is None and "default_values_for_extra_columns" in self.model_fields_set:
            _dict['defaultValuesForExtraColumns'] = None

        # set to None if extra_target_column_action (nullable) is None
        # and model_fields_set contains the field
        if self.extra_target_column_action is None and "extra_target_column_action" in self.model_fields_set:
            _dict['extraTargetColumnAction'] = None

        # set to None if include_deleted_objects (nullable) is None
        # and model_fields_set contains the field
        if self.include_deleted_objects is None and "include_deleted_objects" in self.model_fields_set:
            _dict['includeDeletedObjects'] = None

        # set to None if missing_target_column_action (nullable) is None
        # and model_fields_set contains the field
        if self.missing_target_column_action is None and "missing_target_column_action" in self.model_fields_set:
            _dict['missingTargetColumnAction'] = None

        # set to None if override_row_data (nullable) is None
        # and model_fields_set contains the field
        if self.override_row_data is None and "override_row_data" in self.model_fields_set:
            _dict['overrideRowData'] = None

        # set to None if preserve_sys_id (nullable) is None
        # and model_fields_set contains the field
        if self.preserve_sys_id is None and "preserve_sys_id" in self.model_fields_set:
            _dict['preserveSysId'] = None

        # set to None if table_not_found_action (nullable) is None
        # and model_fields_set contains the field
        if self.table_not_found_action is None and "table_not_found_action" in self.model_fields_set:
            _dict['tableNotFoundAction'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommonRecoveryOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alternateColumnMap": obj.get("alternateColumnMap"),
            "defaultValuesForExtraColumns": obj.get("defaultValuesForExtraColumns"),
            "extraTargetColumnAction": obj.get("extraTargetColumnAction"),
            "includeDeletedObjects": obj.get("includeDeletedObjects"),
            "missingTargetColumnAction": obj.get("missingTargetColumnAction"),
            "overrideRowData": obj.get("overrideRowData"),
            "preserveSysId": obj.get("preserveSysId"),
            "tableNotFoundAction": obj.get("tableNotFoundAction")
        })
        return _obj


