# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class ConnectionConnectivityStatus(BaseModel):
    """
    Specifies connectivity status information for the data-source connection. It represents information such as, if there's at least one active connector, latest time at which any connector(s) in this connection passed health checks, since how long there has been at least one active connector, etc.
    """ # noqa: E501
    connected_since_timestamp_secs: Optional[StrictInt] = Field(default=None, description="This denotes the timestamp in UNIX seconds since which this connection has at least one connector connected to the cluster without any interruptions. This property will NOT be present if none of the connectors in this connection are currently connected to the cluster.", alias="connectedSinceTimestampSecs")
    is_connected: StrictBool = Field(description="Specifies whether the connection has any of its connectors connected.", alias="isConnected")
    last_known_health_ok_timestamp_secs: Optional[StrictInt] = Field(default=None, description="Specifies the most recent known timestamp in UNIX seconds at which any connector(s) in this connection passed the health checks. This property can be present even if no connectors in this connection are currently connected to the cluster.", alias="lastKnownHealthOkTimestampSecs")
    __properties: ClassVar[List[str]] = ["connectedSinceTimestampSecs", "isConnected", "lastKnownHealthOkTimestampSecs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectionConnectivityStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if connected_since_timestamp_secs (nullable) is None
        # and model_fields_set contains the field
        if self.connected_since_timestamp_secs is None and "connected_since_timestamp_secs" in self.model_fields_set:
            _dict['connectedSinceTimestampSecs'] = None

        # set to None if last_known_health_ok_timestamp_secs (nullable) is None
        # and model_fields_set contains the field
        if self.last_known_health_ok_timestamp_secs is None and "last_known_health_ok_timestamp_secs" in self.model_fields_set:
            _dict['lastKnownHealthOkTimestampSecs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectionConnectivityStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connectedSinceTimestampSecs": obj.get("connectedSinceTimestampSecs"),
            "isConnected": obj.get("isConnected"),
            "lastKnownHealthOkTimestampSecs": obj.get("lastKnownHealthOkTimestampSecs")
        })
        return _obj


