# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class ConnectionUpgradeConfig(BaseModel):
    """
    Specifies the config for upgrading an individual connection.
    """ # noqa: E501
    connection_id: Optional[StrictStr] = Field(default=None, description="Specifies the ID of the connection.", alias="connectionId")
    connection_patch_package_url: Optional[StrictStr] = Field(default=None, description="\"Specifies the patch package url to be used for patching a connection in specific. If this is provided, it will override the defaultPatchPackage and tenantPatchPackageUrl URLs. This URL will be used to download the package by connector. It can be http or https and must be IPv4 address or hostname (must be resolvable by the connector).", alias="connectionPatchPackageUrl")
    connection_upgrade_package_url: Optional[StrictStr] = Field(default=None, description="Specifies the upgrade package url to be used for upgrading the connection.", alias="connectionUpgradePackageUrl")
    __properties: ClassVar[List[str]] = ["connectionId", "connectionPatchPackageUrl", "connectionUpgradePackageUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectionUpgradeConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if connection_patch_package_url (nullable) is None
        # and model_fields_set contains the field
        if self.connection_patch_package_url is None and "connection_patch_package_url" in self.model_fields_set:
            _dict['connectionPatchPackageUrl'] = None

        # set to None if connection_upgrade_package_url (nullable) is None
        # and model_fields_set contains the field
        if self.connection_upgrade_package_url is None and "connection_upgrade_package_url" in self.model_fields_set:
            _dict['connectionUpgradePackageUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectionUpgradeConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connectionId": obj.get("connectionId"),
            "connectionPatchPackageUrl": obj.get("connectionPatchPackageUrl"),
            "connectionUpgradePackageUrl": obj.get("connectionUpgradePackageUrl")
        })
        return _obj


