# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.sso_user_principal_parameters import SSOUserPrincipalParameters
from typing import Set
from typing_extensions import Self

class CreatePrincipalRequestParams(BaseModel):
    """
    Specifies the parameters for adding principals to Users and Groups.
    """ # noqa: E501
    principal_type: Optional[StrictStr] = Field(description="Specifies the category of the user or group being added to the Cohesity Cluster.", alias="principalType")
    sso_user_principal_params: Optional[List[SSOUserPrincipalParameters]] = Field(default=None, description="Specifies the properties to be added for the SSO user created on the Cohesity Cluster.", alias="ssoUserPrincipalParams")
    __properties: ClassVar[List[str]] = ["principalType", "ssoUserPrincipalParams"]

    @field_validator('principal_type')
    def principal_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['SSOUser']):
            raise ValueError("must be one of enum values ('SSOUser')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreatePrincipalRequestParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sso_user_principal_params (list)
        _items = []
        if self.sso_user_principal_params:
            for _item_sso_user_principal_params in self.sso_user_principal_params:
                if _item_sso_user_principal_params:
                    _items.append(_item_sso_user_principal_params.to_dict())
            _dict['ssoUserPrincipalParams'] = _items
        # set to None if principal_type (nullable) is None
        # and model_fields_set contains the field
        if self.principal_type is None and "principal_type" in self.model_fields_set:
            _dict['principalType'] = None

        # set to None if sso_user_principal_params (nullable) is None
        # and model_fields_set contains the field
        if self.sso_user_principal_params is None and "sso_user_principal_params" in self.model_fields_set:
            _dict['ssoUserPrincipalParams'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreatePrincipalRequestParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "principalType": obj.get("principalType"),
            "ssoUserPrincipalParams": [SSOUserPrincipalParameters.from_dict(_item) for _item in obj["ssoUserPrincipalParams"]] if obj.get("ssoUserPrincipalParams") is not None else None
        })
        return _obj


