# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self

class CreateOrUpdatePrimaryClusterConnectionParams(BaseModel):
    """
    Specifies the params to initialize the pairing.
    """ # noqa: E501
    password: StrictStr = Field(description="Specifies the password for Cohesity user to use when connecting to the cluster.")
    username: StrictStr = Field(description="Specifies the Cohesity user name used to connect to the cluster.")
    all_endpoints_reachable: Optional[StrictBool] = Field(default=False, description="Specifies if all endpoints on Primary Cluster are reachable.", alias="allEndpointsReachable")
    network_interface: Optional[StrictStr] = Field(default=None, description="Specifies the name of the network interfaces to use for communicating with the Remote Cluster.", alias="networkInterface")
    node_addresses: Annotated[List[StrictStr], Field(min_length=1)] = Field(description="Specifies the VIP or IP addresses of the Nodes on the Primary Cluster to connect with. Hostnames are not supported.", alias="nodeAddresses")
    __properties: ClassVar[List[str]] = ["password", "username", "allEndpointsReachable", "networkInterface", "nodeAddresses"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrUpdatePrimaryClusterConnectionParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if all_endpoints_reachable (nullable) is None
        # and model_fields_set contains the field
        if self.all_endpoints_reachable is None and "all_endpoints_reachable" in self.model_fields_set:
            _dict['allEndpointsReachable'] = None

        # set to None if network_interface (nullable) is None
        # and model_fields_set contains the field
        if self.network_interface is None and "network_interface" in self.model_fields_set:
            _dict['networkInterface'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrUpdatePrimaryClusterConnectionParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "password": obj.get("password"),
            "username": obj.get("username"),
            "allEndpointsReachable": obj.get("allEndpointsReachable") if obj.get("allEndpointsReachable") is not None else False,
            "networkInterface": obj.get("networkInterface"),
            "nodeAddresses": obj.get("nodeAddresses")
        })
        return _obj


