# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cohesity_sdk.cluster.models.office365_app_credentials import Office365AppCredentials
from typing import Set
from typing_extensions import Self

class DeleteAzureApplicationRequestParams(BaseModel):
    """
    Specifies the request parameters for deleting Azure Applications.
    """ # noqa: E501
    access_token: Optional[StrictStr] = Field(description="Specifies the access token for Azure Application access.", alias="accessToken")
    azure_applications_list: Annotated[List[Office365AppCredentials], Field(min_length=1)] = Field(description="Specifies a list of Microsoft365 azure application already created within the Microsoft365 source.", alias="azureApplicationsList")
    azure_tenant_id: Optional[StrictStr] = Field(description="Specifies the Azure Active Directory tenant ID or domain name.", alias="azureTenantId")
    skip_client_id_verification: Optional[StrictBool] = Field(default=None, description="Specifies whether to skip client Id verification on the passed access token.", alias="skipClientIdVerification")
    __properties: ClassVar[List[str]] = ["accessToken", "azureApplicationsList", "azureTenantId", "skipClientIdVerification"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeleteAzureApplicationRequestParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in azure_applications_list (list)
        _items = []
        if self.azure_applications_list:
            for _item_azure_applications_list in self.azure_applications_list:
                if _item_azure_applications_list:
                    _items.append(_item_azure_applications_list.to_dict())
            _dict['azureApplicationsList'] = _items
        # set to None if access_token (nullable) is None
        # and model_fields_set contains the field
        if self.access_token is None and "access_token" in self.model_fields_set:
            _dict['accessToken'] = None

        # set to None if azure_tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.azure_tenant_id is None and "azure_tenant_id" in self.model_fields_set:
            _dict['azureTenantId'] = None

        # set to None if skip_client_id_verification (nullable) is None
        # and model_fields_set contains the field
        if self.skip_client_id_verification is None and "skip_client_id_verification" in self.model_fields_set:
            _dict['skipClientIdVerification'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeleteAzureApplicationRequestParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accessToken": obj.get("accessToken"),
            "azureApplicationsList": [Office365AppCredentials.from_dict(_item) for _item in obj["azureApplicationsList"]] if obj.get("azureApplicationsList") is not None else None,
            "azureTenantId": obj.get("azureTenantId"),
            "skipClientIdVerification": obj.get("skipClientIdVerification")
        })
        return _obj


