# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.diff_graph_node import DiffGraphNode
from cohesity_sdk.cluster.models.diff_graph_node_edge import DiffGraphNodeEdge
from cohesity_sdk.cluster.models.graph_edge import GraphEdge
from typing import Set
from typing_extensions import Self

class DiffGraphNodeRelation(BaseModel):
    """
    Definition of graph node relation difference between two snapshots.
    """ # noqa: E501
    diff_graph_node: Optional[DiffGraphNode] = Field(default=None, alias="diffGraphNode")
    diff_relations: Optional[List[DiffGraphNodeEdge]] = Field(default=None, description="Specifies the all pair of edges/node relations which are added, deleted or modified", alias="diffRelations")
    src_node_id: Optional[StrictStr] = Field(default=None, description="Specifies Unique ID of the source node.", alias="srcNodeId")
    unmodified_relations: Optional[List[GraphEdge]] = Field(default=None, description="Specifies the list of all the edges which are unmodified.", alias="unmodifiedRelations")
    __properties: ClassVar[List[str]] = ["diffGraphNode", "diffRelations", "srcNodeId", "unmodifiedRelations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiffGraphNodeRelation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "src_node_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of diff_graph_node
        if self.diff_graph_node:
            _dict['diffGraphNode'] = self.diff_graph_node.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in diff_relations (list)
        _items = []
        if self.diff_relations:
            for _item_diff_relations in self.diff_relations:
                if _item_diff_relations:
                    _items.append(_item_diff_relations.to_dict())
            _dict['diffRelations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in unmodified_relations (list)
        _items = []
        if self.unmodified_relations:
            for _item_unmodified_relations in self.unmodified_relations:
                if _item_unmodified_relations:
                    _items.append(_item_unmodified_relations.to_dict())
            _dict['unmodifiedRelations'] = _items
        # set to None if diff_relations (nullable) is None
        # and model_fields_set contains the field
        if self.diff_relations is None and "diff_relations" in self.model_fields_set:
            _dict['diffRelations'] = None

        # set to None if unmodified_relations (nullable) is None
        # and model_fields_set contains the field
        if self.unmodified_relations is None and "unmodified_relations" in self.model_fields_set:
            _dict['unmodifiedRelations'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiffGraphNodeRelation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "diffGraphNode": DiffGraphNode.from_dict(obj["diffGraphNode"]) if obj.get("diffGraphNode") is not None else None,
            "diffRelations": [DiffGraphNodeEdge.from_dict(_item) for _item in obj["diffRelations"]] if obj.get("diffRelations") is not None else None,
            "srcNodeId": obj.get("srcNodeId"),
            "unmodifiedRelations": [GraphEdge.from_dict(_item) for _item in obj["unmodifiedRelations"]] if obj.get("unmodifiedRelations") is not None else None
        })
        return _obj


