"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.  # noqa: E501

    The version of the OpenAPI document: 2.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from cohesity_sdk.cluster.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)

def lazy_import():
    from cohesity_sdk.cluster.models.aws_snapshot_manager_params import AwsSnapshotManagerParams
    from cohesity_sdk.cluster.models.common_mssql_protection_group_params import CommonMSSQLProtectionGroupParams
    from cohesity_sdk.cluster.models.exchange_env_job_params import ExchangeEnvJobParams
    from cohesity_sdk.cluster.models.externally_triggered_job_params import ExternallyTriggeredJobParams
    from cohesity_sdk.cluster.models.hyperv_env_job_params import HypervEnvJobParams
    from cohesity_sdk.cluster.models.nas_env_job_params import NasEnvJobParams
    from cohesity_sdk.cluster.models.o365_env_job_params import O365EnvJobParams
    from cohesity_sdk.cluster.models.oracle_env_job_params import OracleEnvJobParams
    from cohesity_sdk.cluster.models.physical_env_job_params import PhysicalEnvJobParams
    from cohesity_sdk.cluster.models.san_env_job_params import SanEnvJobParams
    from cohesity_sdk.cluster.models.vmware_env_job_params import VmwareEnvJobParams
    globals()['AwsSnapshotManagerParams'] = AwsSnapshotManagerParams
    globals()['CommonMSSQLProtectionGroupParams'] = CommonMSSQLProtectionGroupParams
    globals()['ExchangeEnvJobParams'] = ExchangeEnvJobParams
    globals()['ExternallyTriggeredJobParams'] = ExternallyTriggeredJobParams
    globals()['HypervEnvJobParams'] = HypervEnvJobParams
    globals()['NasEnvJobParams'] = NasEnvJobParams
    globals()['O365EnvJobParams'] = O365EnvJobParams
    globals()['OracleEnvJobParams'] = OracleEnvJobParams
    globals()['PhysicalEnvJobParams'] = PhysicalEnvJobParams
    globals()['SanEnvJobParams'] = SanEnvJobParams
    globals()['VmwareEnvJobParams'] = VmwareEnvJobParams


class EnvironmentTypeJobParams(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.

      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.

    """

    allowed_values = {
    }

    validations = {
    }

    additional_properties_type = None

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'aws_snapshot_params': (AwsSnapshotManagerParams,),  # noqa: E501
            'exchange_params': (ExchangeEnvJobParams,),  # noqa: E501
            'externally_triggered_job_params': (ExternallyTriggeredJobParams,),  # noqa: E501
            'hyperv_params': (HypervEnvJobParams,),  # noqa: E501
            'nas_params': (NasEnvJobParams,),  # noqa: E501
            'office365_params': (O365EnvJobParams,),  # noqa: E501
            'oracle_params': (OracleEnvJobParams,),  # noqa: E501
            'physical_params': (PhysicalEnvJobParams,),  # noqa: E501
            'pure_params': (SanEnvJobParams,),  # noqa: E501
            'sql_params': (CommonMSSQLProtectionGroupParams,),  # noqa: E501
            'vmware_params': (VmwareEnvJobParams,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None



    attribute_map = {
        'aws_snapshot_params': 'awsSnapshotParams',  # noqa: E501
        'exchange_params': 'exchangeParams',  # noqa: E501
        'externally_triggered_job_params': 'externallyTriggeredJobParams',  # noqa: E501
        'hyperv_params': 'hypervParams',  # noqa: E501
        'nas_params': 'nasParams',  # noqa: E501
        'office365_params': 'office365Params',  # noqa: E501
        'oracle_params': 'oracleParams',  # noqa: E501
        'physical_params': 'physicalParams',  # noqa: E501
        'pure_params': 'pureParams',  # noqa: E501
        'sql_params': 'sqlParams',  # noqa: E501
        'vmware_params': 'vmwareParams',  # noqa: E501
    }

    _composed_schemas = {}

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """EnvironmentTypeJobParams - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)

            aws_snapshot_params (AwsSnapshotManagerParams): [optional]  # noqa: E501
            exchange_params (ExchangeEnvJobParams): [optional]  # noqa: E501
            externally_triggered_job_params (ExternallyTriggeredJobParams): [optional]  # noqa: E501
            hyperv_params (HypervEnvJobParams): [optional]  # noqa: E501
            nas_params (NasEnvJobParams): [optional]  # noqa: E501
            office365_params (O365EnvJobParams): [optional]  # noqa: E501
            oracle_params (OracleEnvJobParams): [optional]  # noqa: E501
            physical_params (PhysicalEnvJobParams): [optional]  # noqa: E501
            pure_params (SanEnvJobParams): [optional]  # noqa: E501
            sql_params (CommonMSSQLProtectionGroupParams): [optional]  # noqa: E501
            vmware_params (VmwareEnvJobParams): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)


        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)


