# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class EulaConfig(BaseModel):
    """
    Specifies the End User License Agreement acceptance information.
    """ # noqa: E501
    signed_by_user: Optional[StrictStr] = Field(default=None, description="Specifies the login account name for the Cohesity user who accepted the End User License Agreement.", alias="signedByUser")
    signed_time: Optional[StrictInt] = Field(default=None, description="Specifies the time that the End User License Agreement was accepted.", alias="signedTime")
    signed_version: Optional[StrictInt] = Field(default=None, description="Specifies the version of the End User License Agreement that was accepted.", alias="signedVersion")
    __properties: ClassVar[List[str]] = ["signedByUser", "signedTime", "signedVersion"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EulaConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if signed_by_user (nullable) is None
        # and model_fields_set contains the field
        if self.signed_by_user is None and "signed_by_user" in self.model_fields_set:
            _dict['signedByUser'] = None

        # set to None if signed_time (nullable) is None
        # and model_fields_set contains the field
        if self.signed_time is None and "signed_time" in self.model_fields_set:
            _dict['signedTime'] = None

        # set to None if signed_version (nullable) is None
        # and model_fields_set contains the field
        if self.signed_version is None and "signed_version" in self.model_fields_set:
            _dict['signedVersion'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EulaConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "signedByUser": obj.get("signedByUser"),
            "signedTime": obj.get("signedTime"),
            "signedVersion": obj.get("signedVersion")
        })
        return _obj


