# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.recover_google_spanner_new_source_config import RecoverGoogleSpannerNewSourceConfig
from typing import Set
from typing_extensions import Self

class GCPTargetParamsForRecoverGoogleSpanner(BaseModel):
    """
    Specifies the recovery target params for Google Spanner target config.
    """ # noqa: E501
    cloud_storage_bucket_name: Optional[StrictStr] = Field(default=None, description="The Google Cloud Storage bucket name for Spanner recovery.", alias="cloudStorageBucketName")
    max_workers: StrictInt = Field(description="Maximum number of Dataflow workers to use (cost limiter).", alias="maxWorkers")
    new_source_config: Optional[RecoverGoogleSpannerNewSourceConfig] = Field(default=None, alias="newSourceConfig")
    recover_to_new_source: StrictBool = Field(description="Specifies the parameter whether the recovery should be performed to a new or an existing target.", alias="recoverToNewSource")
    vpc_network: StrictStr = Field(description="VPC network name for Dataflow processing.", alias="vpcNetwork")
    vpc_subnet: StrictStr = Field(description="Subnet name within the VPC for Dataflow processing.", alias="vpcSubnet")
    __properties: ClassVar[List[str]] = ["cloudStorageBucketName", "maxWorkers", "newSourceConfig", "recoverToNewSource", "vpcNetwork", "vpcSubnet"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GCPTargetParamsForRecoverGoogleSpanner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of new_source_config
        if self.new_source_config:
            _dict['newSourceConfig'] = self.new_source_config.to_dict()
        # set to None if cloud_storage_bucket_name (nullable) is None
        # and model_fields_set contains the field
        if self.cloud_storage_bucket_name is None and "cloud_storage_bucket_name" in self.model_fields_set:
            _dict['cloudStorageBucketName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GCPTargetParamsForRecoverGoogleSpanner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cloudStorageBucketName": obj.get("cloudStorageBucketName"),
            "maxWorkers": obj.get("maxWorkers") if obj.get("maxWorkers") is not None else 10,
            "newSourceConfig": RecoverGoogleSpannerNewSourceConfig.from_dict(obj["newSourceConfig"]) if obj.get("newSourceConfig") is not None else None,
            "recoverToNewSource": obj.get("recoverToNewSource"),
            "vpcNetwork": obj.get("vpcNetwork"),
            "vpcSubnet": obj.get("vpcSubnet")
        })
        return _obj


