# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.data_tiering_target import DataTieringTarget
from cohesity_sdk.cluster.models.downtiering_file_age_policy import DowntieringFileAgePolicy
from cohesity_sdk.cluster.models.file_filtering_policy import FileFilteringPolicy
from cohesity_sdk.cluster.models.file_level_data_lock_config import FileLevelDataLockConfig
from cohesity_sdk.cluster.models.file_size_policy import FileSizePolicy
from cohesity_sdk.cluster.models.filter_ip_config import FilterIpConfig
from cohesity_sdk.cluster.models.nas_throttling_config import NasThrottlingConfig
from cohesity_sdk.cluster.models.snapshot_label import SnapshotLabel
from cohesity_sdk.cluster.models.uptiering_file_age_policy import UptieringFileAgePolicy
from typing import Set
from typing_extensions import Self

class NasEnvJobParams(BaseModel):
    """
    Specifies additional special parameters that are applicable only to Types of 'kGenericNas' type.
    """ # noqa: E501
    enable_audit_logging: Optional[StrictBool] = Field(default=False, description="Specifies whether to audit log the file tiering activity.", alias="enableAuditLogging")
    file_path: Optional[FileFilteringPolicy] = Field(default=None, alias="filePath")
    file_size: Optional[FileSizePolicy] = Field(default=None, alias="fileSize")
    include_all_files: Optional[StrictBool] = Field(default=False, description="If set, all files in the view will be uptiered regardless of file_select_policy, num_file_access, hot_file_window, file_size constraints.", alias="includeAllFiles")
    target: Optional[DataTieringTarget] = None
    uptiering_file_age: Optional[UptieringFileAgePolicy] = Field(default=None, alias="uptieringFileAge")
    auto_orphan_data_cleanup: Optional[StrictBool] = Field(default=True, description="Specifies whether to remove the orphan data from the target if the symlink is removed from the source.", alias="autoOrphanDataCleanup")
    downtiering_file_age: Optional[DowntieringFileAgePolicy] = Field(default=None, alias="downtieringFileAge")
    skip_back_symlink: Optional[StrictBool] = Field(default=True, description="Specifies whether to create a symlink for the migrated data from source to target.", alias="skipBackSymlink")
    backup_existing_snapshot: Optional[StrictBool] = Field(default=None, description="Specifies that snapshot label is not set for Data-Protect Netapp Volumes backup. If field is set to true, existing oldest snapshot is used for backup and subsequent incremental will be selected in ascending order of snapshot create time on the source. If snapshot label is set, this field is set to false.", alias="backupExistingSnapshot")
    continue_on_error: Optional[StrictBool] = Field(default=None, description="Specifies whether or not the Protection Group should continue regardless of whether or not an error was encountered during protection group run.", alias="continueOnError")
    enable_faster_incremental_backups: Optional[StrictBool] = Field(default=None, description="Specifies whether this job will enable faster incremental backups using change list or similar APIs", alias="enableFasterIncrementalBackups")
    encryption_enabled: Optional[StrictBool] = Field(default=None, description="Specifies whether the protection group should use encryption while backup or not.", alias="encryptionEnabled")
    file_lock_config: Optional[FileLevelDataLockConfig] = Field(default=None, alias="fileLockConfig")
    file_path_filters: Optional[FileFilteringPolicy] = Field(default=None, alias="filePathFilters")
    filter_ip_config: Optional[FilterIpConfig] = Field(default=None, alias="filterIpConfig")
    modify_source_permissions: Optional[StrictBool] = Field(default=None, description="Specifies if the NAS source permissions should be modified internally to allow backups.", alias="modifySourcePermissions")
    nas_protocol: Optional[StrictStr] = Field(default=None, description="Specifies the preferred protocol to use if this device supports multiple protocols.", alias="nasProtocol")
    nfs_version_preference: Optional[StrictStr] = Field(default=None, description="Specifies the preference of NFS version to be backed up if a volume supports multiple versions of NFS.", alias="nfsVersionPreference")
    snapshot_label: Optional[SnapshotLabel] = Field(default=None, alias="snapshotLabel")
    throttling_config: Optional[NasThrottlingConfig] = Field(default=None, alias="throttlingConfig")
    use_changelist: Optional[StrictBool] = Field(default=None, description="Specify whether to use the Isilon Changelist API to directly discover changed files/directories for faster incremental backup. Cohesity will keep an extra snapshot which will be deleted by the next successful backup.", alias="useChangelist")
    __properties: ClassVar[List[str]] = ["enableAuditLogging", "filePath", "fileSize", "includeAllFiles", "target", "uptieringFileAge", "autoOrphanDataCleanup", "downtieringFileAge", "skipBackSymlink", "backupExistingSnapshot", "continueOnError", "enableFasterIncrementalBackups", "encryptionEnabled", "fileLockConfig", "filePathFilters", "filterIpConfig", "modifySourcePermissions", "nasProtocol", "nfsVersionPreference", "snapshotLabel", "throttlingConfig", "useChangelist"]

    @field_validator('nas_protocol')
    def nas_protocol_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kNoProtocol', 'kNfs3', 'kNfs4_1', 'kCifs1', 'kCifs2', 'kCifs3']):
            raise ValueError("must be one of enum values ('kNoProtocol', 'kNfs3', 'kNfs4_1', 'kCifs1', 'kCifs2', 'kCifs3')")
        return value

    @field_validator('nfs_version_preference')
    def nfs_version_preference_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kNfs3', 'kNfs4_1']):
            raise ValueError("must be one of enum values ('kNfs3', 'kNfs4_1')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NasEnvJobParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of file_path
        if self.file_path:
            _dict['filePath'] = self.file_path.to_dict()
        # override the default output from pydantic by calling `to_dict()` of file_size
        if self.file_size:
            _dict['fileSize'] = self.file_size.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of uptiering_file_age
        if self.uptiering_file_age:
            _dict['uptieringFileAge'] = self.uptiering_file_age.to_dict()
        # override the default output from pydantic by calling `to_dict()` of downtiering_file_age
        if self.downtiering_file_age:
            _dict['downtieringFileAge'] = self.downtiering_file_age.to_dict()
        # override the default output from pydantic by calling `to_dict()` of file_lock_config
        if self.file_lock_config:
            _dict['fileLockConfig'] = self.file_lock_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of file_path_filters
        if self.file_path_filters:
            _dict['filePathFilters'] = self.file_path_filters.to_dict()
        # override the default output from pydantic by calling `to_dict()` of filter_ip_config
        if self.filter_ip_config:
            _dict['filterIpConfig'] = self.filter_ip_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of snapshot_label
        if self.snapshot_label:
            _dict['snapshotLabel'] = self.snapshot_label.to_dict()
        # override the default output from pydantic by calling `to_dict()` of throttling_config
        if self.throttling_config:
            _dict['throttlingConfig'] = self.throttling_config.to_dict()
        # set to None if enable_audit_logging (nullable) is None
        # and model_fields_set contains the field
        if self.enable_audit_logging is None and "enable_audit_logging" in self.model_fields_set:
            _dict['enableAuditLogging'] = None

        # set to None if include_all_files (nullable) is None
        # and model_fields_set contains the field
        if self.include_all_files is None and "include_all_files" in self.model_fields_set:
            _dict['includeAllFiles'] = None

        # set to None if target (nullable) is None
        # and model_fields_set contains the field
        if self.target is None and "target" in self.model_fields_set:
            _dict['target'] = None

        # set to None if auto_orphan_data_cleanup (nullable) is None
        # and model_fields_set contains the field
        if self.auto_orphan_data_cleanup is None and "auto_orphan_data_cleanup" in self.model_fields_set:
            _dict['autoOrphanDataCleanup'] = None

        # set to None if skip_back_symlink (nullable) is None
        # and model_fields_set contains the field
        if self.skip_back_symlink is None and "skip_back_symlink" in self.model_fields_set:
            _dict['skipBackSymlink'] = None

        # set to None if backup_existing_snapshot (nullable) is None
        # and model_fields_set contains the field
        if self.backup_existing_snapshot is None and "backup_existing_snapshot" in self.model_fields_set:
            _dict['backupExistingSnapshot'] = None

        # set to None if continue_on_error (nullable) is None
        # and model_fields_set contains the field
        if self.continue_on_error is None and "continue_on_error" in self.model_fields_set:
            _dict['continueOnError'] = None

        # set to None if enable_faster_incremental_backups (nullable) is None
        # and model_fields_set contains the field
        if self.enable_faster_incremental_backups is None and "enable_faster_incremental_backups" in self.model_fields_set:
            _dict['enableFasterIncrementalBackups'] = None

        # set to None if encryption_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.encryption_enabled is None and "encryption_enabled" in self.model_fields_set:
            _dict['encryptionEnabled'] = None

        # set to None if modify_source_permissions (nullable) is None
        # and model_fields_set contains the field
        if self.modify_source_permissions is None and "modify_source_permissions" in self.model_fields_set:
            _dict['modifySourcePermissions'] = None

        # set to None if nas_protocol (nullable) is None
        # and model_fields_set contains the field
        if self.nas_protocol is None and "nas_protocol" in self.model_fields_set:
            _dict['nasProtocol'] = None

        # set to None if nfs_version_preference (nullable) is None
        # and model_fields_set contains the field
        if self.nfs_version_preference is None and "nfs_version_preference" in self.model_fields_set:
            _dict['nfsVersionPreference'] = None

        # set to None if use_changelist (nullable) is None
        # and model_fields_set contains the field
        if self.use_changelist is None and "use_changelist" in self.model_fields_set:
            _dict['useChangelist'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NasEnvJobParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "enableAuditLogging": obj.get("enableAuditLogging") if obj.get("enableAuditLogging") is not None else False,
            "filePath": FileFilteringPolicy.from_dict(obj["filePath"]) if obj.get("filePath") is not None else None,
            "fileSize": FileSizePolicy.from_dict(obj["fileSize"]) if obj.get("fileSize") is not None else None,
            "includeAllFiles": obj.get("includeAllFiles") if obj.get("includeAllFiles") is not None else False,
            "target": DataTieringTarget.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "uptieringFileAge": UptieringFileAgePolicy.from_dict(obj["uptieringFileAge"]) if obj.get("uptieringFileAge") is not None else None,
            "autoOrphanDataCleanup": obj.get("autoOrphanDataCleanup") if obj.get("autoOrphanDataCleanup") is not None else True,
            "downtieringFileAge": DowntieringFileAgePolicy.from_dict(obj["downtieringFileAge"]) if obj.get("downtieringFileAge") is not None else None,
            "skipBackSymlink": obj.get("skipBackSymlink") if obj.get("skipBackSymlink") is not None else True,
            "backupExistingSnapshot": obj.get("backupExistingSnapshot"),
            "continueOnError": obj.get("continueOnError"),
            "enableFasterIncrementalBackups": obj.get("enableFasterIncrementalBackups"),
            "encryptionEnabled": obj.get("encryptionEnabled"),
            "fileLockConfig": FileLevelDataLockConfig.from_dict(obj["fileLockConfig"]) if obj.get("fileLockConfig") is not None else None,
            "filePathFilters": FileFilteringPolicy.from_dict(obj["filePathFilters"]) if obj.get("filePathFilters") is not None else None,
            "filterIpConfig": FilterIpConfig.from_dict(obj["filterIpConfig"]) if obj.get("filterIpConfig") is not None else None,
            "modifySourcePermissions": obj.get("modifySourcePermissions"),
            "nasProtocol": obj.get("nasProtocol"),
            "nfsVersionPreference": obj.get("nfsVersionPreference"),
            "snapshotLabel": SnapshotLabel.from_dict(obj["snapshotLabel"]) if obj.get("snapshotLabel") is not None else None,
            "throttlingConfig": NasThrottlingConfig.from_dict(obj["throttlingConfig"]) if obj.get("throttlingConfig") is not None else None,
            "useChangelist": obj.get("useChangelist")
        })
        return _obj


