# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.onedrive_backup_params import OnedriveBackupParams
from cohesity_sdk.cluster.models.outlook_backup_params import OutlookBackupParams
from typing import Set
from typing_extensions import Self

class O365EnvJobParams(BaseModel):
    """
    Specifies job parameters applicable for all 'kVMware' Environment type Protection Sources in a Protection Job.
    """ # noqa: E501
    onedrive_backup_params: Optional[OnedriveBackupParams] = Field(default=None, alias="onedriveBackupParams")
    outlook_backup_params: Optional[OutlookBackupParams] = Field(default=None, alias="outlookBackupParams")
    __properties: ClassVar[List[str]] = ["onedriveBackupParams", "outlookBackupParams"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of O365EnvJobParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of onedrive_backup_params
        if self.onedrive_backup_params:
            _dict['onedriveBackupParams'] = self.onedrive_backup_params.to_dict()
        # override the default output from pydantic by calling `to_dict()` of outlook_backup_params
        if self.outlook_backup_params:
            _dict['outlookBackupParams'] = self.outlook_backup_params.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of O365EnvJobParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "onedriveBackupParams": OnedriveBackupParams.from_dict(obj["onedriveBackupParams"]) if obj.get("onedriveBackupParams") is not None else None,
            "outlookBackupParams": OutlookBackupParams.from_dict(obj["outlookBackupParams"]) if obj.get("outlookBackupParams") is not None else None
        })
        return _obj


