# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.file_filtering_policy import FileFilteringPolicy
from typing import Set
from typing_extensions import Self

class OnedriveBackupParams(BaseModel):
    """
    Specifies OneDrive job parameters applicable for all Office365 Environment type Protection Sources in a Protection group.
    """ # noqa: E501
    file_path_filter: Optional[FileFilteringPolicy] = Field(default=None, alias="filePathFilter")
    should_backup_onedrive: Optional[StrictBool] = Field(default=None, alias="shouldBackupOnedrive")
    __properties: ClassVar[List[str]] = ["filePathFilter", "shouldBackupOnedrive"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OnedriveBackupParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of file_path_filter
        if self.file_path_filter:
            _dict['filePathFilter'] = self.file_path_filter.to_dict()
        # set to None if should_backup_onedrive (nullable) is None
        # and model_fields_set contains the field
        if self.should_backup_onedrive is None and "should_backup_onedrive" in self.model_fields_set:
            _dict['shouldBackupOnedrive'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OnedriveBackupParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "filePathFilter": FileFilteringPolicy.from_dict(obj["filePathFilter"]) if obj.get("filePathFilter") is not None else None,
            "shouldBackupOnedrive": obj.get("shouldBackupOnedrive")
        })
        return _obj


