# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Set
from typing_extensions import Self

class PostgresSourceRegistrationParams(BaseModel):
    """
    Specifies parameters to register a Postgres source.
    """ # noqa: E501
    password: StrictStr = Field(description="Specifies the password to access target entity.")
    username: StrictStr = Field(description="Specifies the username to access target entity.")
    pg_bin: Optional[StrictStr] = Field(default=None, description="Specifies the directory containing the PostgreSQL binaries.", alias="pgBin")
    pg_host: Optional[StrictStr] = Field(default=None, description="Specifies the host for the Postgres source.", alias="pgHost")
    pg_port: StrictInt = Field(description="Specifies the port for the Postgres source.", alias="pgPort")
    archive_mode: StrictBool = Field(description="Specifies the archive mode for the Postgres source.", alias="archiveMode")
    check_db_connection: StrictBool = Field(description="Specifies whether to check the database connection for the Postgres source.", alias="checkDbConnection")
    environment_variables: Optional[List[StrictStr]] = Field(default=None, description="Specifies the environment variables for the Postgres source.", alias="environmentVariables")
    hosts: Annotated[List[StrictStr], Field(min_length=1)] = Field(description="Specifies the IPs/hostnames for the nodes forming the Postgres source cluster.")
    kerberos_keytab: Optional[StrictStr] = Field(default=None, description="Specifies the Kerberos keytab file for the Postgres source authentication.", alias="kerberosKeytab")
    kerberos_principal: Optional[StrictStr] = Field(default=None, description="Specifies the Kerberos principal for the Postgres source authentication.", alias="kerberosPrincipal")
    script_dir: StrictStr = Field(description="Specifies the directory containing the scripts used to interact with the Postgres source.", alias="scriptDir")
    source_name: StrictStr = Field(description="Specifies user friendly unique name provided for registering Postgres source.", alias="sourceName")
    ssl_certificate_dir: Optional[StrictStr] = Field(default=None, description="Specifies the directory containing the SSL certificates for the Postgres source authentication.", alias="sslCertificateDir")
    __properties: ClassVar[List[str]] = ["password", "username", "pgBin", "pgHost", "pgPort", "archiveMode", "checkDbConnection", "environmentVariables", "hosts", "kerberosKeytab", "kerberosPrincipal", "scriptDir", "sourceName", "sslCertificateDir"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostgresSourceRegistrationParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if pg_bin (nullable) is None
        # and model_fields_set contains the field
        if self.pg_bin is None and "pg_bin" in self.model_fields_set:
            _dict['pgBin'] = None

        # set to None if pg_host (nullable) is None
        # and model_fields_set contains the field
        if self.pg_host is None and "pg_host" in self.model_fields_set:
            _dict['pgHost'] = None

        # set to None if environment_variables (nullable) is None
        # and model_fields_set contains the field
        if self.environment_variables is None and "environment_variables" in self.model_fields_set:
            _dict['environmentVariables'] = None

        # set to None if kerberos_keytab (nullable) is None
        # and model_fields_set contains the field
        if self.kerberos_keytab is None and "kerberos_keytab" in self.model_fields_set:
            _dict['kerberosKeytab'] = None

        # set to None if kerberos_principal (nullable) is None
        # and model_fields_set contains the field
        if self.kerberos_principal is None and "kerberos_principal" in self.model_fields_set:
            _dict['kerberosPrincipal'] = None

        # set to None if ssl_certificate_dir (nullable) is None
        # and model_fields_set contains the field
        if self.ssl_certificate_dir is None and "ssl_certificate_dir" in self.model_fields_set:
            _dict['sslCertificateDir'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostgresSourceRegistrationParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "password": obj.get("password"),
            "username": obj.get("username"),
            "pgBin": obj.get("pgBin"),
            "pgHost": obj.get("pgHost"),
            "pgPort": obj.get("pgPort"),
            "archiveMode": obj.get("archiveMode"),
            "checkDbConnection": obj.get("checkDbConnection"),
            "environmentVariables": obj.get("environmentVariables"),
            "hosts": obj.get("hosts"),
            "kerberosKeytab": obj.get("kerberosKeytab"),
            "kerberosPrincipal": obj.get("kerberosPrincipal"),
            "scriptDir": obj.get("scriptDir"),
            "sourceName": obj.get("sourceName"),
            "sslCertificateDir": obj.get("sslCertificateDir")
        })
        return _obj


