# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class ProtectionRunsInPolicySummary(BaseModel):
    """
    Specifies the aggregated summary of the Protection Runs.
    """ # noqa: E501
    number_of_archival_runs: Optional[StrictInt] = Field(default=None, description="Specifies the total number of Archival Runs using the current Protection Policy.", alias="numberOfArchivalRuns")
    number_of_protection_runs: Optional[StrictInt] = Field(default=None, description="Specifies the total number of Protection Runs by the given Protection Policy.", alias="numberOfProtectionRuns")
    number_of_replication_runs: Optional[StrictInt] = Field(default=None, description="Specifies the total number of Replication Runs using the current Protection Policy.", alias="numberOfReplicationRuns")
    number_of_successful_archival_runs: Optional[StrictInt] = Field(default=None, description="Specifies the number of total successful Archival Runs using the current Protection Policy.", alias="numberOfSuccessfulArchivalRuns")
    number_of_successful_protection_runs: Optional[StrictInt] = Field(default=None, description="Specifies the number of successful Protection Runs using the current Protection Policy.", alias="numberOfSuccessfulProtectionRuns")
    number_of_successful_replication_runs: Optional[StrictInt] = Field(default=None, description="Specifies the number of total successful Replication Runs using the current Protection Policy.", alias="numberOfSuccessfulReplicationRuns")
    __properties: ClassVar[List[str]] = ["numberOfArchivalRuns", "numberOfProtectionRuns", "numberOfReplicationRuns", "numberOfSuccessfulArchivalRuns", "numberOfSuccessfulProtectionRuns", "numberOfSuccessfulReplicationRuns"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProtectionRunsInPolicySummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if number_of_archival_runs (nullable) is None
        # and model_fields_set contains the field
        if self.number_of_archival_runs is None and "number_of_archival_runs" in self.model_fields_set:
            _dict['numberOfArchivalRuns'] = None

        # set to None if number_of_protection_runs (nullable) is None
        # and model_fields_set contains the field
        if self.number_of_protection_runs is None and "number_of_protection_runs" in self.model_fields_set:
            _dict['numberOfProtectionRuns'] = None

        # set to None if number_of_replication_runs (nullable) is None
        # and model_fields_set contains the field
        if self.number_of_replication_runs is None and "number_of_replication_runs" in self.model_fields_set:
            _dict['numberOfReplicationRuns'] = None

        # set to None if number_of_successful_archival_runs (nullable) is None
        # and model_fields_set contains the field
        if self.number_of_successful_archival_runs is None and "number_of_successful_archival_runs" in self.model_fields_set:
            _dict['numberOfSuccessfulArchivalRuns'] = None

        # set to None if number_of_successful_protection_runs (nullable) is None
        # and model_fields_set contains the field
        if self.number_of_successful_protection_runs is None and "number_of_successful_protection_runs" in self.model_fields_set:
            _dict['numberOfSuccessfulProtectionRuns'] = None

        # set to None if number_of_successful_replication_runs (nullable) is None
        # and model_fields_set contains the field
        if self.number_of_successful_replication_runs is None and "number_of_successful_replication_runs" in self.model_fields_set:
            _dict['numberOfSuccessfulReplicationRuns'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProtectionRunsInPolicySummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "numberOfArchivalRuns": obj.get("numberOfArchivalRuns"),
            "numberOfProtectionRuns": obj.get("numberOfProtectionRuns"),
            "numberOfReplicationRuns": obj.get("numberOfReplicationRuns"),
            "numberOfSuccessfulArchivalRuns": obj.get("numberOfSuccessfulArchivalRuns"),
            "numberOfSuccessfulProtectionRuns": obj.get("numberOfSuccessfulProtectionRuns"),
            "numberOfSuccessfulReplicationRuns": obj.get("numberOfSuccessfulReplicationRuns")
        })
        return _obj


