# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.archival_target_summary_info import ArchivalTargetSummaryInfo
from cohesity_sdk.cluster.models.cloud_spin_target import CloudSpinTarget
from cohesity_sdk.cluster.models.object import Object
from typing import Set
from typing_extensions import Self

class RestoreInfo(BaseModel):
    """
    Specifies the info regarding a snapshot
    """ # noqa: E501
    archival_target_info: Optional[ArchivalTargetSummaryInfo] = Field(default=None, alias="archivalTargetInfo")
    attempt_number: Optional[StrictInt] = Field(default=None, description="Specifies the attempt number of the job run to restore from.", alias="attemptNumber")
    cloud_deploy_target: Optional[CloudSpinTarget] = Field(default=None, alias="cloudDeployTarget")
    cloud_replication_target: Optional[CloudSpinTarget] = Field(default=None, alias="cloudReplicationTarget")
    object_info: Optional[Object] = Field(default=None, alias="objectInfo")
    parent_object_info: Optional[Object] = Field(default=None, alias="parentObjectInfo")
    protection_group_id: Optional[StrictStr] = Field(default=None, description="Specifies the protection group id of the run responsible for the snapshot", alias="protectionGroupId")
    run_start_time_usecs: Optional[StrictInt] = Field(default=None, description="Specifies the start time specified as a Unix epoch Timestamp (in microseconds).", alias="runStartTimeUsecs")
    snapshot_relative_dir_path: Optional[StrictStr] = Field(default=None, description="Specifies the relative path to the directory containing the entity's snapshot.", alias="snapshotRelativeDirPath")
    view_name: Optional[StrictStr] = Field(default=None, description="The name of the view where the object's snapshot is located.", alias="viewName")
    vm_had_independent_disks: Optional[StrictBool] = Field(default=None, description="Specifies this is applicable only to VMs and is set to true when the VM being recovered or cloned contained independent disks when it was backed up.", alias="vmHadIndependentDisks")
    __properties: ClassVar[List[str]] = ["archivalTargetInfo", "attemptNumber", "cloudDeployTarget", "cloudReplicationTarget", "objectInfo", "parentObjectInfo", "protectionGroupId", "runStartTimeUsecs", "snapshotRelativeDirPath", "viewName", "vmHadIndependentDisks"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RestoreInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of archival_target_info
        if self.archival_target_info:
            _dict['archivalTargetInfo'] = self.archival_target_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cloud_deploy_target
        if self.cloud_deploy_target:
            _dict['cloudDeployTarget'] = self.cloud_deploy_target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cloud_replication_target
        if self.cloud_replication_target:
            _dict['cloudReplicationTarget'] = self.cloud_replication_target.to_dict()
        # override the default output from pydantic by calling `to_dict()` of object_info
        if self.object_info:
            _dict['objectInfo'] = self.object_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of parent_object_info
        if self.parent_object_info:
            _dict['parentObjectInfo'] = self.parent_object_info.to_dict()
        # set to None if attempt_number (nullable) is None
        # and model_fields_set contains the field
        if self.attempt_number is None and "attempt_number" in self.model_fields_set:
            _dict['attemptNumber'] = None

        # set to None if protection_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.protection_group_id is None and "protection_group_id" in self.model_fields_set:
            _dict['protectionGroupId'] = None

        # set to None if run_start_time_usecs (nullable) is None
        # and model_fields_set contains the field
        if self.run_start_time_usecs is None and "run_start_time_usecs" in self.model_fields_set:
            _dict['runStartTimeUsecs'] = None

        # set to None if snapshot_relative_dir_path (nullable) is None
        # and model_fields_set contains the field
        if self.snapshot_relative_dir_path is None and "snapshot_relative_dir_path" in self.model_fields_set:
            _dict['snapshotRelativeDirPath'] = None

        # set to None if view_name (nullable) is None
        # and model_fields_set contains the field
        if self.view_name is None and "view_name" in self.model_fields_set:
            _dict['viewName'] = None

        # set to None if vm_had_independent_disks (nullable) is None
        # and model_fields_set contains the field
        if self.vm_had_independent_disks is None and "vm_had_independent_disks" in self.model_fields_set:
            _dict['vmHadIndependentDisks'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RestoreInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "archivalTargetInfo": ArchivalTargetSummaryInfo.from_dict(obj["archivalTargetInfo"]) if obj.get("archivalTargetInfo") is not None else None,
            "attemptNumber": obj.get("attemptNumber"),
            "cloudDeployTarget": CloudSpinTarget.from_dict(obj["cloudDeployTarget"]) if obj.get("cloudDeployTarget") is not None else None,
            "cloudReplicationTarget": CloudSpinTarget.from_dict(obj["cloudReplicationTarget"]) if obj.get("cloudReplicationTarget") is not None else None,
            "objectInfo": Object.from_dict(obj["objectInfo"]) if obj.get("objectInfo") is not None else None,
            "parentObjectInfo": Object.from_dict(obj["parentObjectInfo"]) if obj.get("parentObjectInfo") is not None else None,
            "protectionGroupId": obj.get("protectionGroupId"),
            "runStartTimeUsecs": obj.get("runStartTimeUsecs"),
            "snapshotRelativeDirPath": obj.get("snapshotRelativeDirPath"),
            "viewName": obj.get("viewName"),
            "vmHadIndependentDisks": obj.get("vmHadIndependentDisks")
        })
        return _obj


