# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.restore_config_payload import RestoreConfigPayload
from typing import Set
from typing_extensions import Self

class RestoreConfig(BaseModel):
    """
    Specifies the restore config of the cluster.
    """ # noqa: E501
    config: Optional[RestoreConfigPayload] = None
    last_updated_timestamp_sec: Optional[StrictInt] = Field(default=None, description="Specifies the timestamp fo the last update made to this config.")
    service_name: Optional[StrictStr] = Field(default=None, description="Specifies the service name of the restore config.", alias="serviceName")
    __properties: ClassVar[List[str]] = ["config", "last_updated_timestamp_sec", "serviceName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RestoreConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # set to None if last_updated_timestamp_sec (nullable) is None
        # and model_fields_set contains the field
        if self.last_updated_timestamp_sec is None and "last_updated_timestamp_sec" in self.model_fields_set:
            _dict['last_updated_timestamp_sec'] = None

        # set to None if service_name (nullable) is None
        # and model_fields_set contains the field
        if self.service_name is None and "service_name" in self.model_fields_set:
            _dict['serviceName'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RestoreConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": RestoreConfigPayload.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "last_updated_timestamp_sec": obj.get("last_updated_timestamp_sec"),
            "serviceName": obj.get("serviceName")
        })
        return _obj


