# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Set
from typing_extensions import Self

class SubsiteItem(BaseModel):
    """
    Specifies a M365 Subsite item. Currently used for subsites of teams/group root site's subsites.
    """ # noqa: E501
    absolute_item_path: Optional[StrictStr] = Field(default=None, description="Specifies the unique path of the item as indexed by the document system. The path includes subsite IDs and document library IDs to ensure uniqueness. This property is only applicable to items within subsites.", alias="absoluteItemPath")
    relative_subsite_path: Optional[StrictStr] = Field(default=None, description="Specifies the relative path of this subsite item from subsite level.", alias="relativeSubsitePath")
    site_type: Optional[StrictStr] = Field(default=None, description="Specifies the M365 Teams/Groups subsite item type.", alias="siteType")
    site_uuid: Optional[StrictStr] = Field(default=None, description="Specifies the uuid of the site of the document library item. This is needed for Teams and Groups having subsites, as multiple items across different subsites can be selected for granular recovery. This is only applicable for the subsite items.", alias="siteUuid")
    __properties: ClassVar[List[str]] = ["absoluteItemPath", "relativeSubsitePath", "siteType", "siteUuid"]

    @field_validator('site_type')
    def site_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['GroupSubsite', 'PrivateChannelSubsite']):
            raise ValueError("must be one of enum values ('GroupSubsite', 'PrivateChannelSubsite')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SubsiteItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if absolute_item_path (nullable) is None
        # and model_fields_set contains the field
        if self.absolute_item_path is None and "absolute_item_path" in self.model_fields_set:
            _dict['absoluteItemPath'] = None

        # set to None if relative_subsite_path (nullable) is None
        # and model_fields_set contains the field
        if self.relative_subsite_path is None and "relative_subsite_path" in self.model_fields_set:
            _dict['relativeSubsitePath'] = None

        # set to None if site_type (nullable) is None
        # and model_fields_set contains the field
        if self.site_type is None and "site_type" in self.model_fields_set:
            _dict['siteType'] = None

        # set to None if site_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.site_uuid is None and "site_uuid" in self.model_fields_set:
            _dict['siteUuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SubsiteItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "absoluteItemPath": obj.get("absoluteItemPath"),
            "relativeSubsitePath": obj.get("relativeSubsitePath"),
            "siteType": obj.get("siteType"),
            "siteUuid": obj.get("siteUuid")
        })
        return _obj


