# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.agent_upgrade_task_info import AgentUpgradeTaskInfo
from cohesity_sdk.cluster.models.analysis_task_info import AnalysisTaskInfo
from cohesity_sdk.cluster.models.backup_task_info import BackupTaskInfo
from cohesity_sdk.cluster.models.basic_task_info import BasicTaskInfo
from cohesity_sdk.cluster.models.bulk_install_app_task_info import BulkInstallAppTaskInfo
from cohesity_sdk.cluster.models.clone_task_info import CloneTaskInfo
from cohesity_sdk.cluster.models.recovery_task_info import RecoveryTaskInfo
from cohesity_sdk.cluster.models.tiering_task_info import TieringTaskInfo
from typing import Set
from typing_extensions import Self

class TaskNotification(BaseModel):
    """
    Structure that captures Task Notifications for a user.
    """ # noqa: E501
    agent_upgrade_task: Optional[AgentUpgradeTaskInfo] = Field(default=None, alias="agentUpgradeTask")
    analysis_task: Optional[AnalysisTaskInfo] = Field(default=None, alias="analysisTask")
    backup_task: Optional[BackupTaskInfo] = Field(default=None, alias="backupTask")
    bulk_install_app_task: Optional[BulkInstallAppTaskInfo] = Field(default=None, alias="bulkInstallAppTask")
    clone_task: Optional[CloneTaskInfo] = Field(default=None, alias="cloneTask")
    created_time_secs: Optional[StrictInt] = Field(default=None, description="Timestamp at which the notification was created.", alias="createdTimeSecs")
    description: Optional[StrictStr] = Field(default=None, description="Description holds the actual notification text generated for the event.")
    dismissed: Optional[StrictBool] = Field(default=None, description="Dismissed keeps track of whether a notification has been seen or not. User may choose to dismiss individual event or all notifications at once. Nil or 0 value represents false.")
    dismissed_time_secs: Optional[StrictInt] = Field(default=None, description="Timestamp at which user dismissed this notification event.", alias="dismissedTimeSecs")
    field_message_task: Optional[BasicTaskInfo] = Field(default=None, alias="fieldMessageTask")
    id: Optional[StrictStr] = Field(default=None, description="id identifies a user notification event uniquely. This can also be used to dismiss individual notifications.")
    recovery_task: Optional[RecoveryTaskInfo] = Field(default=None, alias="recoveryTask")
    status: Optional[StrictStr] = Field(default=None, description="Status of the task. Status of the task. 'kSuccess' indicates that task completed successfully. 'kError' indicates that task encountered errors.")
    task_type: Optional[StrictStr] = Field(default=None, description="Task type denotes which type of task this notification is for. This param is used to reflect the taskType. 'Restore' notification type is generated upon completion of Restore tasks. 'Clone' notification type is generated upon completion of Clone tasks. 'BackupNow' notification type is generated upon completion of Backup tasks. 'FieldMessage' notification type is generated when field message from Cohesity support is created. 'bulkInstallApp' notification type is generated from bulk install app 'tiering' notification type is generated upon completion of tiering tasks. 'analysis' notification type is generated upon completion of analysis tasks. 'agentUpgradeTask' notification type is generated upon completion of upgrade task.", alias="taskType")
    tiering_task: Optional[TieringTaskInfo] = Field(default=None, alias="tieringTask")
    visited: Optional[StrictBool] = Field(default=None, description="Visited keeps track of whether a notification has been seen or not.")
    visited_time_secs: Optional[StrictInt] = Field(default=None, description="Timestamp at which user visited this notification event.", alias="visitedTimeSecs")
    __properties: ClassVar[List[str]] = ["agentUpgradeTask", "analysisTask", "backupTask", "bulkInstallAppTask", "cloneTask", "createdTimeSecs", "description", "dismissed", "dismissedTimeSecs", "fieldMessageTask", "id", "recoveryTask", "status", "taskType", "tieringTask", "visited", "visitedTimeSecs"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['kSuccess', 'kError']):
            raise ValueError("must be one of enum values ('kSuccess', 'kError')")
        return value

    @field_validator('task_type')
    def task_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['restore', 'clone', 'backupNow', 'fieldMessage', 'bulkInstallApp', 'tiering', 'analysis', 'agentUpgradeTask']):
            raise ValueError("must be one of enum values ('restore', 'clone', 'backupNow', 'fieldMessage', 'bulkInstallApp', 'tiering', 'analysis', 'agentUpgradeTask')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaskNotification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agent_upgrade_task
        if self.agent_upgrade_task:
            _dict['agentUpgradeTask'] = self.agent_upgrade_task.to_dict()
        # override the default output from pydantic by calling `to_dict()` of analysis_task
        if self.analysis_task:
            _dict['analysisTask'] = self.analysis_task.to_dict()
        # override the default output from pydantic by calling `to_dict()` of backup_task
        if self.backup_task:
            _dict['backupTask'] = self.backup_task.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bulk_install_app_task
        if self.bulk_install_app_task:
            _dict['bulkInstallAppTask'] = self.bulk_install_app_task.to_dict()
        # override the default output from pydantic by calling `to_dict()` of clone_task
        if self.clone_task:
            _dict['cloneTask'] = self.clone_task.to_dict()
        # override the default output from pydantic by calling `to_dict()` of field_message_task
        if self.field_message_task:
            _dict['fieldMessageTask'] = self.field_message_task.to_dict()
        # override the default output from pydantic by calling `to_dict()` of recovery_task
        if self.recovery_task:
            _dict['recoveryTask'] = self.recovery_task.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tiering_task
        if self.tiering_task:
            _dict['tieringTask'] = self.tiering_task.to_dict()
        # set to None if created_time_secs (nullable) is None
        # and model_fields_set contains the field
        if self.created_time_secs is None and "created_time_secs" in self.model_fields_set:
            _dict['createdTimeSecs'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if dismissed (nullable) is None
        # and model_fields_set contains the field
        if self.dismissed is None and "dismissed" in self.model_fields_set:
            _dict['dismissed'] = None

        # set to None if dismissed_time_secs (nullable) is None
        # and model_fields_set contains the field
        if self.dismissed_time_secs is None and "dismissed_time_secs" in self.model_fields_set:
            _dict['dismissedTimeSecs'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if task_type (nullable) is None
        # and model_fields_set contains the field
        if self.task_type is None and "task_type" in self.model_fields_set:
            _dict['taskType'] = None

        # set to None if visited (nullable) is None
        # and model_fields_set contains the field
        if self.visited is None and "visited" in self.model_fields_set:
            _dict['visited'] = None

        # set to None if visited_time_secs (nullable) is None
        # and model_fields_set contains the field
        if self.visited_time_secs is None and "visited_time_secs" in self.model_fields_set:
            _dict['visitedTimeSecs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaskNotification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agentUpgradeTask": AgentUpgradeTaskInfo.from_dict(obj["agentUpgradeTask"]) if obj.get("agentUpgradeTask") is not None else None,
            "analysisTask": AnalysisTaskInfo.from_dict(obj["analysisTask"]) if obj.get("analysisTask") is not None else None,
            "backupTask": BackupTaskInfo.from_dict(obj["backupTask"]) if obj.get("backupTask") is not None else None,
            "bulkInstallAppTask": BulkInstallAppTaskInfo.from_dict(obj["bulkInstallAppTask"]) if obj.get("bulkInstallAppTask") is not None else None,
            "cloneTask": CloneTaskInfo.from_dict(obj["cloneTask"]) if obj.get("cloneTask") is not None else None,
            "createdTimeSecs": obj.get("createdTimeSecs"),
            "description": obj.get("description"),
            "dismissed": obj.get("dismissed"),
            "dismissedTimeSecs": obj.get("dismissedTimeSecs"),
            "fieldMessageTask": BasicTaskInfo.from_dict(obj["fieldMessageTask"]) if obj.get("fieldMessageTask") is not None else None,
            "id": obj.get("id"),
            "recoveryTask": RecoveryTaskInfo.from_dict(obj["recoveryTask"]) if obj.get("recoveryTask") is not None else None,
            "status": obj.get("status"),
            "taskType": obj.get("taskType"),
            "tieringTask": TieringTaskInfo.from_dict(obj["tieringTask"]) if obj.get("tieringTask") is not None else None,
            "visited": obj.get("visited"),
            "visitedTimeSecs": obj.get("visitedTimeSecs")
        })
        return _obj


