# coding: utf-8

"""
    Cohesity REST API

    Cohesity API provides a RESTful interface to access the various data management operations on Cohesity cluster and Helios.

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cohesity_sdk.cluster.models.recovery_time_range_info import RecoveryTimeRangeInfo
from typing import Set
from typing_extensions import Self

class TimeRangeInfo(BaseModel):
    """
    Information about a set of disjoint, possibly annotated time ranges.
    """ # noqa: E501
    error_message: Optional[StrictStr] = Field(default=None, description="Error (if any) associated with the time range.", alias="errorMessage")
    time_ranges: Optional[List[RecoveryTimeRangeInfo]] = Field(default=None, description="The set of time ranges, each of which may be tagged with its job. These ranges will be non-overlapping and sorted by increasing start time.", alias="timeRanges")
    user_message: Optional[StrictStr] = Field(default=None, description="User message (if any) associated with the time range.", alias="userMessage")
    __properties: ClassVar[List[str]] = ["errorMessage", "timeRanges", "userMessage"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TimeRangeInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in time_ranges (list)
        _items = []
        if self.time_ranges:
            for _item_time_ranges in self.time_ranges:
                if _item_time_ranges:
                    _items.append(_item_time_ranges.to_dict())
            _dict['timeRanges'] = _items
        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if time_ranges (nullable) is None
        # and model_fields_set contains the field
        if self.time_ranges is None and "time_ranges" in self.model_fields_set:
            _dict['timeRanges'] = None

        # set to None if user_message (nullable) is None
        # and model_fields_set contains the field
        if self.user_message is None and "user_message" in self.model_fields_set:
            _dict['userMessage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TimeRangeInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "errorMessage": obj.get("errorMessage"),
            "timeRanges": [RecoveryTimeRangeInfo.from_dict(_item) for _item in obj["timeRanges"]] if obj.get("timeRanges") is not None else None,
            "userMessage": obj.get("userMessage")
        })
        return _obj


